# ============================================================
#   GdkDragContext
# ============================================================

[[enum]]
ctype = "GdkDragAction"
prefix = "GDK_"

[[enum]]
ctype = "GdkDragCancelReason"
prefix = "GDK_"

[[enum]]
ctype = "GdkDragProtocol"
prefix = "GDK_"

[[method]]
id = "gdk_drag_context_list_targets"
bind = false
# not supposed to be used by applications

[[method]]
id = "::action-changed"

[[method.parameter]]
name = "action"
ctype = "GdkDragAction"

[[method]]
id = "::cancel"

[[method.parameter]]
name = "reason"
ctype = "GdkDragCancelReason"