# ============================================================
#   GdkEvent
# ============================================================

[[enum]]
ctype = "GdkEventType"
prefix = "GDK_"
ignore = "GDK_DOUBLE_BUTTON_PRESS GDK_TRIPLE_BUTTON_PRESS"

[[enum]]
ctype = "GdkEventMask"
prefix = "GDK_"

[[enum]]
ctype = "GdkVisibilityState"
prefix = "GDK_"

[[enum]]
ctype = "GdkScrollDirection"
prefix = "GDK_"

[[enum]]
ctype = "GdkNotifyType"
prefix = "GDK_"

[[enum]]
ctype = "GdkCrossingMode"
prefix = "GDK_"

[[enum]]
ctype = "GdkPropertyState"
prefix = "GDK_"

[[enum]]
ctype = "GdkWindowState"
prefix = "GDK_"

[[enum]]
ctype = "GdkSettingAction"
prefix = "GDK_"

[[enum]]
ctype = "GdkOwnerChange"
prefix = "GDK_"

[[record]]
ctype = "GdkEventSequence"

[[record]]
ctype = "GdkEventAny"

[[record]]
ctype = "GdkEventButton"

[[record]]
ctype = "GdkEventExpose"

[[record]]
ctype = "GdkEventVisibility"

[[record]]
ctype = "GdkEventMotion"

[[record]]
ctype = "GdkEventScroll"

[[record]]
ctype = "GdkEventKey"

[[record]]
ctype = "GdkEventCrossing"

[[record]]
ctype = "GdkEventFocus"

[[record]]
ctype = "GdkEventConfigure"

[[record]]
ctype = "GdkEventProperty"

[[record]]
ctype = "GdkEventSelection"

[[record]]
ctype = "GdkEventOwnerChange"

[[record]]
ctype = "GdkEventProximity"

[[record]]
ctype = "GdkEventDND"

[[record]]
ctype = "GdkEventWindowState"

[[record]]
ctype = "GdkEventSetting"

[[record]]
ctype = "GdkEventTouch"

[[record]]
ctype = "GdkEventGrabBroken"

[[record]]
ctype = "GdkEventGrabBroken"

[[record]]
ctype = "GdkEventTouchpadSwipe"

[[record]]
ctype = "GdkEventTouchpadPinch"

[[record]]
ctype = "GdkEventPadButton"

[[record]]
ctype = "GdkEventPadAxis"

[[record]]
ctype = "GdkEventPadGroupMode"

[[record]]
ctype = "GdkEvent"
ada = "Gdk_Event_Record"

[[record.union]]
value = "GDK_NOTHING"
field = "any"

[[record.union]]
value = "GDK_DELETE"
field = "any"

[[record.union]]
value = "GDK_DESTROY"
field = "any"

[[record.union]]
value = "GDK_EXPOSE"
field = "expose"

[[record.union]]
value = "GDK_MOTION_NOTIFY"
field = "motion"

[[record.union]]
value = "GDK_BUTTON_PRESS"
field = "button"

[[record.union]]
value = "GDK_2BUTTON_PRESS"
field = "button"

[[record.union]]
value = "GDK_3BUTTON_PRESS"
field = "button"

[[record.union]]
value = "GDK_BUTTON_RELEASE"
field = "button"

[[record.union]]
value = "GDK_KEY_PRESS"
field = "key"

[[record.union]]
value = "GDK_KEY_RELEASE"
field = "key"

[[record.union]]
value = "GDK_ENTER_NOTIFY"
field = "crossing"

[[record.union]]
value = "GDK_LEAVE_NOTIFY"
field = "crossing"

[[record.union]]
value = "GDK_FOCUS_CHANGE"
field = "focus_change"

[[record.union]]
value = "GDK_CONFIGURE"
field = "configure"

[[record.union]]
value = "GDK_MAP"
field = "any"

[[record.union]]
value = "GDK_UNMAP"
field = "any"

[[record.union]]
value = "GDK_PROPERTY_NOTIFY"
field = "property"

[[record.union]]
value = "GDK_SELECTION_CLEAR"
field = "selection"

[[record.union]]
value = "GDK_SELECTION_REQUEST"
field = "selection"

[[record.union]]
value = "GDK_SELECTION_NOTIFY"
field = "selection"

[[record.union]]
value = "GDK_PROXIMITY_IN"
field = "proximity"

[[record.union]]
value = "GDK_PROXIMITY_OUT"
field = "proximity"

[[record.union]]
value = "GDK_DRAG_ENTER"
field = "dnd"

[[record.union]]
value = "GDK_DRAG_LEAVE"
field = "dnd"

[[record.union]]
value = "GDK_DRAG_MOTION"
field = "dnd"

[[record.union]]
value = "GDK_DRAG_STATUS"
field = "dnd"

[[record.union]]
value = "GDK_DROP_START"
field = "dnd"

[[record.union]]
value = "GDK_DROP_FINISHED"
field = "dnd"

[[record.union]]
value = "GDK_CLIENT_EVENT"
field = "any"

[[record.union]]
value = "GDK_VISIBILITY_NOTIFY"
field = "visibility"

[[record.union]]
value = "GDK_SCROLL"
field = "scroll"

[[record.union]]
value = "GDK_WINDOW_STATE"
field = "window_state"

[[record.union]]
value = "GDK_SETTING"
field = "setting"

[[record.union]]
value = "GDK_OWNER_CHANGE"
field = "owner_change"

[[record.union]]
value = "GDK_GRAB_BROKEN"
field = "grab_broken"

[[record.union]]
value = "GDK_DAMAGE"
field = "expose"

[[record.union]]
value = "GDK_TOUCH_BEGIN"
field = "touch"

[[record.union]]
value = "GDK_TOUCH_UPDATE"
field = "touch"

[[record.union]]
value = "GDK_TOUCH_END"
field = "touch"

[[record.union]]
value = "GDK_TOUCH_CANCEL"
field = "touch"

[[record.union]]
value = "GDK_TOUCHPAD_SWIPE"
field = "touchpad_swipe"

[[record.union]]
value = "GDK_TOUCHPAD_PINCH"
field = "touchpad_pinch"

[[record.union]]
value = "GDK_PAD_BUTTON_PRESS"
field = "pad_button"

[[record.union]]
value = "GDK_PAD_BUTTON_RELEASE"
field = "pad_button"

[[record.union]]
value = "GDK_PAD_RING"
field = "pad_axis"

[[record.union]]
value = "GDK_PAD_STRIP"
field = "pad_axis"

[[record.union]]
value = "GDK_PAD_GROUP_MODE"
field = "pad_group_mode"

[[method]]
id = "gdk_event_get_coords"
return = "void"

[[method]]
id = "gdk_event_get_root_coords"
return = "void"

[[method]]
id = "gdk_event_get_axis"
return = "void"

[[method]]
id = "gdk_event_get_scroll_direction"
return = "void"

[[method]]
id = "gdk_event_get_scroll_deltas"
return = "void"
# These are getters provided by gtk+ itself. They are reused from our own misc.c file, because we want GtkAda to raise exceptions instead. See <extra> below

[[method]]
id = "gdk_event_get_button"
bind = false

[[method]]
id = "gdk_event_get_state"
bind = false

[[method]]
id = "gdk_event_get_click_count"
bind = false

[[method]]
id = "gdk_event_get_keyval"
bind = false

[[method]]
id = "gdk_event_get_keycode"
bind = false
# Avoid circular dependencies Event->Device->Display->Event

[[method]]
id = "gdk_event_get_device"
bind = false

[[method]]
id = "gdk_event_get_source_device"
bind = false

[[method]]
id = "gdk_event_set_device"
bind = false

[[method]]
id = "gdk_event_set_source_device"
bind = false

[[method]]
id = "gdk_event_get_screen"
bind = false

[[method]]
id = "gdk_event_set_screen"
bind = false

[[method]]
id = "gdk_event_get_seat"
return = "GObject*"

[[function]]
id = "gdk_events_pending"
ada = "Events_Pending"

[[method]]
id = "gdk_events_get_angle"
ada = "Get_Angle"

[[method]]
id = "gdk_events_get_center"
ada = "Get_Center"

[[method]]
id = "gdk_events_get_distance"
ada = "Get_Distance"

[[function]]
id = "gdk_set_show_events"
ada = "Set_Show_Events"

[[function]]
id = "gdk_get_show_events"
ada = "Get_Show_Events"

[extra]
body = '''

   function From_Address (C : System.Address) return Gdk_Event is
      function Convert is new Ada.Unchecked_Conversion
           (Glib.C_Proxy, Gdk_Event);
   begin
      return Convert (Glib.C_Proxy'(Glib.To_Proxy (C)));
   end From_Address;

   function To_Address (C : Gdk_Event) return System.Address is
      function Convert is new Ada.Unchecked_Conversion
           (Gdk_Event, Glib.C_Proxy);
   begin
      return Glib.To_Address (Convert (C));
   end To_Address;

   function Get_Event (Value : Glib.Values.GValue) return Gdk_Event is
      function Convert is new Ada.Unchecked_Conversion
           (Glib.C_Proxy, Gdk_Event);
   begin
      return Convert (Glib.Values.Get_Proxy (Value));
   end Get_Event;

   function To_Event (Event : access Gdk_Event_Button) return Gdk_Event is
      type Gdk_Event_Button_Access is access all Gdk_Event_Button;
      function Convert is new Ada.Unchecked_Conversion
           (Gdk_Event_Button_Access, Gdk_Event);
   begin
      return Convert (Gdk_Event_Button_Access (Event));
   end To_Event;

   function To_Event (Event : access Gdk_Event_Key) return Gdk_Event is
      type Gdk_Event_Key_Access is access all Gdk_Event_Key;
      function Convert is new Ada.Unchecked_Conversion
         (Gdk_Event_Key_Access, Gdk_Event);
   begin
      return Convert (Gdk_Event_Key_Access (Event));
   end To_Event;
       '''

[[extra.with_spec]]
pkg = "Glib.Values"

[[extra.spec]]
text = '''

         Double_Button_Press : constant Gdk_Event_Type := Gdk_2button_Press;
         Triple_Button_Press : constant Gdk_Event_Type := Gdk_3button_Press;

         Button_Primary   : constant Gint := 1;
         Button_Secondary : constant Gint := 3;
         Button_Middle    : constant Gint := 2;
         --  The primary button is typically the left mouse button, or the
         --  right button in a left-handed setup. The secondary button is the
         --  other one.

         function From_Address (C : System.Address) return Gdk_Event;
         --  Convert a C handler to the matching Event structure.

         function To_Address (C : Gdk_Event) return System.Address;
         --  Convert an event to the underlying C handler.

         function Get_Event (Value : Glib.Values.GValue) return Gdk_Event;
         --  Convert a value into a Gdk_Event.

         function To_Event (Event : access Gdk_Event_Button) return Gdk_Event;
         function To_Event (Event : access Gdk_Event_Key) return Gdk_Event;
         --  Cast Event into a Gdk_Event, which can be used to call some of
         --  subprograms in the API. The return value is a pointer to Event,
         --  which should therefore remain valid as long as the pointer is in
         --  use.

   -------------------------------
   -- Some constants used below --
   -------------------------------
   --  This constants have the '-1' since in some cases gtk itself uses
   --  the extrema to return some meaningful value (for instance, the result
   --  of Get_Area can have the values Guint16'Last to mean the whole area).

   Invalid_Gdouble_Value : constant Gdouble := Gdouble'Last - 1.0;
   Invalid_Gint_Value    : constant Gint    := Gint'Last - 1;
   Invalid_Guint_Value   : constant Guint   := Guint'Last - 1;
   Invalid_Guint32_Value : constant Guint32 := Guint32'Last - 1;
   Invalid_Gulong_Value  : constant Gulong  := Gulong'Last - 1;

   pragma Export (C, Invalid_Gdouble_Value, "ada_gdk_invalid_gdouble_value");
   pragma Export (C, Invalid_Gint_Value, "ada_gdk_invalid_gint_value");
   pragma Export (C, Invalid_Guint_Value, "ada_gdk_invalid_guint_value");
   pragma Export (C, Invalid_Guint32_Value, "ada_gdk_invalid_guint32_value");
   pragma Export (C, Invalid_Gulong_Value, "ada_gdk_invalid_gulong_value");
       '''

[[extra.type]]
ctype = "GdkEvent*"
ada = "Gdk_Event"
text = '''

         type Gdk_Event is access all Gdk_Event_Record;
         pragma No_Strict_Aliasing (Gdk_Event);
       '''

[[extra.gir_element]]
xml = '''
<gir:method xmlns:c="http://www.gtk.org/introspection/c/1.0" xmlns:gir="http://www.gtk.org/introspection/core/1.0" name="Get_Button" c:identifier="ada_gdk_event_get_button">
         <gir:doc>Extract the button number from an event</gir:doc>
         <gir:return-value><gir:type name="guint" c:type="guint" /></gir:return-value>
       </gir:method>
       '''

[[extra.gir_element]]
xml = '''
<gir:method xmlns:c="http://www.gtk.org/introspection/c/1.0" xmlns:gir="http://www.gtk.org/introspection/core/1.0" name="Get_State" c:identifier="ada_gdk_event_get_state">
         <gir:doc>State of the mouse buttons and keyboard keys just prior to the event</gir:doc>
         <gir:return-value><gir:type name="GdkModifierType" c:type="GdkModifierType" /></gir:return-value>
       </gir:method>
       '''

[[extra.gir_element]]
xml = '''
<gir:method xmlns:c="http://www.gtk.org/introspection/c/1.0" xmlns:gir="http://www.gtk.org/introspection/core/1.0" name="Get_Key_Val" c:identifier="ada_gdk_event_get_keyval">
         <gir:doc>Code of the key that was pressed (and that generated the event)</gir:doc>
         <gir:return-value><gir:type name="GdkKeyType" c:type="GdkKeyType" /></gir:return-value>
       </gir:method>
       '''

[[extra.gir_element]]
xml = '''
<gir:method xmlns:c="http://www.gtk.org/introspection/c/1.0" xmlns:gir="http://www.gtk.org/introspection/core/1.0" name="Get_Keycode" c:identifier="ada_gdk_event_get_keycode">
         <gir:doc>Hardware key code of the key that was pressed</gir:doc>
         <gir:return-value><gir:type name="guint" c:type="guint" /></gir:return-value>
       </gir:method>

       '''

[doc]
group = "Gdk, the low-level API"

[[parameter]]
name = "self"
ada = "Event"