# ============================================================
#   GdkSeat
# ============================================================

[[enum]]
ctype = "GdkSeatCapabilities"

[[list]]
ada = "Gdk_Seat_List"
ctype = "GdkSeat*"

[[method]]
id = "gdk_seat_get_slaves"
return = "DeviceList"

[[method]]
id = "gdk_seat_get_display"
return = "GObject*"

[[method]]
id = "::tool-added"

[[method.parameter]]
name = "tool"
ctype = "GObject*"

[[method]]
id = "::tool-removed"

[[method.parameter]]
name = "tool"
ctype = "GObject*"

[[method]]
id = "::device-added"

[[method.parameter]]
name = "device"
ctype = "GObject*"

[[method]]
id = "::device-removed"

[[method.parameter]]
name = "device"
ctype = "GObject*"

[extra]

[[extra.with_spec]]
pkg = "Gdk.Types"