# ============================================================
#   GtkAlignment
# ============================================================

[doc]
screenshot = "gtk-alignment"
testgtk = "create_alignment.adb"

[[parameter]]
name = "self"
ada = "Alignment"

[[method]]
id = "gtkada_GtkAlignment_get_xalign"

[[method]]
id = "gtkada_GtkAlignment_get_xscale"

[[method]]
id = "gtkada_GtkAlignment_get_yalign"

[[method]]
id = "gtkada_GtkAlignment_get_yscale"