# ============================================================
#   GtkAssistant
# ============================================================

[doc]
group = "Windows"
testgtk = "create_assistant.adb"

[[parameter]]
name = "self"
ada = "Assistant"

[[enum]]
ctype = "GtkAssistantPageType"
prefix = ""