# ============================================================
#   GtkArrow
# ============================================================

[doc]
screenshot = "gtk-arrow"
testgtk = "create_arrow.adb"

[[parameter]]
name = "self"
ada = "Arrow"