# ============================================================
#   GtkApplication
# ============================================================

[[enum]]
ctype = "GtkApplicationInhibitFlags"

[[method]]
id = "gtk_application_get_windows"
return = "WidgetList"