# ============================================================
#   GtkAboutDialog
# ============================================================

[doc]
group = "Windows"
gtkada_demo = "create_about.adb"

[[parameter]]
name = "self"
ada = "About"

[[enum]]
ctype = "GtkLicense"