# ============================================================
#   GtkAspectFrame
# ============================================================

[doc]
group = "Layout Containers"
gtkada_demo = "create_frame.adb"

[[parameter]]
name = "self"
ada = "Aspect_Frame"

[[method]]
id = "gtk_aspect_frame_new"

[[method.parameter]]
name = "label"
default = "\"\""
allow_none = "1"