# ============================================================
#   GtkArrow
# ============================================================

[doc]
screenshot = "gtk-arrow"
gtkada_demo = "create_arrow.adb"

[[parameter]]
name = "self"
ada = "Arrow"