# ============================================================
#   GtkBin
# ============================================================

[doc]
group = "Abstract base classes"

[[parameter]]
name = "self"
ada = "Bin"