# ============================================================
#   GtkCellEditable
# ============================================================

[doc]
group = "Trees and Lists"

[[parameter]]
name = "self"
ada = "Cell_Editable"