# ============================================================
#   GtkCheckMenuItem
# ============================================================

[[parameter]]
name = "self"
ada = "Check_Menu_Item"

[[method]]
id = "gtk_check_menu_item_new"
bind = false

[[method]]
id = "gtk_check_menu_item_new_with_label"
ada = "Gtk_New"

[[method.parameter]]
name = "label"
default = "\"\""
allow_none = "1"