# ============================================================
#   GtkCssProvider
# ============================================================

[[method]]
id = "::parsing-error"
bind = false

[[method]]
id = "gtk_css_provider_load_from_data"

[[method.parameter]]
name = "data"
ctype = "char*"

[[method.parameter]]
name = "length"
ada = ""
default = "-1"

[[method.parameter]]
name = "error"
direction = "access"

[[method]]
id = "gtk_css_provider_load_from_path"

[[method.parameter]]
name = "error"
direction = "access"

[[method]]
id = "gtk_css_provider_load_from_file"
bind = false
# needs GFile