# ============================================================
#   GtkCalendar
# ============================================================

[doc]
screenshot = "gtk-calendar"
group = "Selectors"
testgtk = "create_calendar.adb"

[[parameter]]
name = "self"
ada = "Calendar"

[[enum]]
ctype = "GtkCalendarDisplayOptions"
prefix = "GTK_CALENDAR_"