# ============================================================
#   GtkCellRenderer
# ============================================================

[[parameter]]
name = "self"
ada = "Cell"

[[enum]]
ctype = "GtkCellRendererState"

[[enum]]
ctype = "GtkCellRendererMode"

[[method]]
id = "gtk_cell_renderer_get_size"

[[method.parameter]]
name = "cell_area"
ctype = "GdkRectangle**"

[[list]]
ada = "Cell_Renderer_List"
ctype = "GtkCellRenderer"