# ============================================================
#   GtkCssSection
# ============================================================

[[enum]]
ctype = "GtkCssSectionType"

[[method]]
id = "gtk_css_section_get_file"
bind = false
# needs GFile