# ============================================================
#   GtkCheckButton
# ============================================================

[doc]
screenshot = "gtk-check_button"
group = "Buttons and Toggles"
gtkada_demo = "create_check_buttons.adb"

[[parameter]]
name = "self"
ada = "Check_Button"

[[method]]
id = "gtk_check_button_new"
bind = false

[[method]]
id = "gtk_check_button_new_with_label"
ada = "Gtk_New"

[method.doc]
text = "Create a check button. if Label is null, then no widget is associated with the button, and any widget can be added to the button (with Gtk.Container.Add)."

[[method.parameter]]
name = "label"
default = "\"\""
allow_none = "1"