# ============================================================
#   GtkEntryCompletion
# ============================================================

[doc]
group = "Numeric/Text Data Entry"

[[parameter]]
name = "self"
ada = "Completion"