# ============================================================
#   GtkExpander
# ============================================================

[doc]
screenshot = "gtk-expanded"
group = "Layout containers"

[[parameter]]
name = "self"
ada = "Expander"