# ============================================================
#   GtkFontSelectionDialog
# ============================================================

[doc]
screenshot = "gtk-fontsel"
group = "Selectors"
gtkada_demo = "create_font_selection.adb"
text = '''
This widget provides a dialog for selecting a font.
See also Gtk.Font_Selection.
      '''

[[parameter]]
name = "self"
ada = "Dialog"