# ============================================================
#   GtkFixed
# ============================================================

[doc]
screenshot = "gtk-fixed"
group = "Layout containers"
gtkada_demo = "create_fixed.adb"

[[parameter]]
name = "self"
ada = "Fixed"

[[method]]
id = "gtk_fixed_put"

[method.doc]
text = "Add Widget to a Fixed container at the given position. X indicates the horizontal position to place the widget at. Y is the vertical position to place the widget at."

[[method]]
id = "gtk_fixed_move"

[method.doc]
text = "Move a child of a GtkFixed container to the given position. X indicates the horizontal position to place the widget at. Y is the vertical position to place the widget at."

[[method]]
id = "gtk_fixed_set_has_window"

[[method.parameter]]
name = "has_window"
default = "False"