# ============================================================
#   GtkFileChooserButton
# ============================================================

[doc]
group = "Buttons and Toggles"

[[parameter]]
name = "self"
ada = "Button"