# ============================================================
#   GtkHandleBox
# ============================================================
obsolescent = true

[[parameter]]
name = "self"
ada = "Handle_Box"