# ============================================================
#   GtkHScrollbar
# ============================================================
into = "GtkScrollbar"

[[parameter]]
name = "self"
ada = "Scrollbar"

[[type]]
name = "Gtk_Hscrollbar"
subtype = true

[[method]]
id = "gtk_hscrollbar_new"
ada = "Gtk_New_Hscrollbar"

[[method]]
id = "gtk_hscrollbar_get_type"
ada = "Hscrollbar_Get_Type"