# ============================================================
#   GtkHScale
# ============================================================
into = "GtkScale"

[[parameter]]
name = "self"
ada = "Scale"

[[type]]
name = "Gtk_Hscale"
subtype = true

[[method]]
id = "gtk_hscale_new"
ada = "Gtk_New_Hscale"

[[method.parameter]]
name = "adjustment"
default = "null"

[[method]]
id = "gtk_hscale_new_with_range"
ada = "Gtk_New_Hscale"

[[method]]
id = "gtk_hscale_get_type"
ada = "Hscale_Get_Type"