# ============================================================
#   GtkMenuToolButton
# ============================================================

[[parameter]]
name = "self"
ada = "Button"

[[method]]
id = "gtk_menu_tool_button_new"

[[method.parameter]]
name = "self"
ada = "Menu"

[[method.parameter]]
name = "icon_widget"
default = "null"

[[method]]
id = "gtk_menu_tool_button_new_from_stock"

[[method.parameter]]
name = "self"
ada = "Menu"

[[method]]
id = "gtk_menu_tool_button_get_menu"
return = "GtkMenu"