# ============================================================
#   GtkProgressBar
# ============================================================

[doc]
screenshot = "gtk-progress_bar"
group = "Display widgets"
testgtk = "create_progress.adb"

[[parameter]]
name = "self"
ada = "Progress_Bar"