# ============================================================
#   GtkRecentChooser
# ============================================================

[[virtual_method]]
id = "*"
bind = false

[[parameter]]
name = "self"
ada = "Chooser"

[[method]]
id = "gtk_recent_chooser_get_items"
return = "RecentInfoList"

[[enum]]
ctype = "GtkRecentSortType"
# These functions return the length separately, not needed in Ada

[[method]]
id = "gtk_recent_chooser_get_uris"
bind = false

[[method]]
id = "gtk_recent_chooser_list_filters"
return = "RecentFilterSList"