# ============================================================
#   GtkRange
# ============================================================

[doc]
screenshot = "gtk-range"
gtkada_demo = "create_range.adb"

[[parameter]]
name = "self"
ada = "The_Range"