# ============================================================
#   GtkRange
# ============================================================

[doc]
screenshot = "gtk-range"
testgtk = "create_range.adb"

[[parameter]]
name = "self"
ada = "The_Range"