# ============================================================
#   GtkRadioToolButton
# ============================================================

[[method]]
id = "gtk_radio_tool_button_new"

[[method.parameter]]
name = "group"
ctype = "WidgetSList"

[[method]]
id = "gtk_radio_tool_button_new_from_stock"

[[method.parameter]]
name = "group"
ctype = "WidgetSList"

[[method]]
id = "gtk_radio_tool_button_set_group"

[[method.parameter]]
name = "group"
ctype = "WidgetSList"

[[method]]
id = "gtk_radio_tool_button_get_group"
return = "WidgetSList"

[[method]]
id = "gtk_radio_tool_button_new_from_widget"
bind = false
# gir file misses Group parameter

[[method]]
id = "gtk_radio_tool_button_new_with_stock_from_widget"
bind = false
# gir file misses Group parameter