# ============================================================
#   GtkSeparatorToolItem
# ============================================================

[doc]
group = "Menus and Toolbars"

[[parameter]]
name = "self"
ada = "Item"