# ============================================================
#   GtkStatusbar
# ============================================================

[doc]
screenshot = "gtk-status_bar"
group = "Display widgets"
gtkada_demo = "create_status.adb"

[[parameter]]
name = "self"
ada = "Statusbar"

[[parameter]]
name = "context"
type = "Context_Id"

[[parameter]]
name = "context_id"
ada = "context"
type = "Context_Id"

[[parameter]]
name = "message_id"
ada = "Message"
type = "Message_Id"

[[method]]
id = "gtk_statusbar_get_context_id"
return = "Context_Id"

[[method]]
id = "gtkada_GtkStatusbar_get_messages"
return = "MessagesList"

[[method]]
id = "gtk_statusbar_push"
return = "Message_Id"

[extra]

[[extra.type]]
text = '''

   type Context_Id is new Guint;
   type Message_Id is new Guint;
        '''