# ============================================================
#   GtkScrolledWindow
# ============================================================

[[parameter]]
name = "self"
ada = "Scrolled_Window"

[[method]]
id = "gtk_scrolled_window_new"

[[method.parameter]]
name = "hadjustment"
default = "null"

[[method.parameter]]
name = "vadjustment"
default = "null"

[[method]]
id = "gtk_scrolled_window_get_hscrollbar"
return = "GtkScrollbar"

[[method]]
id = "gtk_scrolled_window_get_vscrollbar"
return = "GtkScrollbar"