# ============================================================
#   GtkStyleContext
# ============================================================

[[enum]]
ctype = "GtkStyleContextPrintFlags"

[[method]]
id = "gtk_style_context_has_region"
return_as_param = "Is_Defined"

[[method]]
id = "gtk_style_context_list_classes"
return = "StringList"

[[method]]
id = "gtk_style_context_list_regions"
return = "StringList"

[[method]]
id = "gtk_style_context_get_valist"
bind = false
# needs valist

[[method]]
id = "gtk_style_context_get_style_valist"
bind = false
# needs valist

[[method]]
id = "gtk_style_context_lookup_color"
return_as_param = "Found"

[[method]]
id = "gtk_style_context_state_is_running"
return_as_param = "Is_Running"

[[method]]
id = "gtk_style_context_lookup_icon_set"
bind = false
# in GtkIconSet

[[function]]
id = "gtk_render_handle"

[[function]]
id = "gtk_render_check"

[[function]]
id = "gtk_render_option"

[[function]]
id = "gtk_render_arrow"

[[function]]
id = "gtk_render_background"

[[function]]
id = "gtk_render_frame"

[[function]]
id = "gtk_render_expander"

[[function]]
id = "gtk_render_focus"

[[function]]
id = "gtk_render_layout"

[[function]]
id = "gtk_render_line"

[[function]]
id = "gtk_render_slider"

[[function]]
id = "gtk_render_frame_gap"

[[function]]
id = "gtk_render_extension"

[[function]]
id = "gtk_render_activity"
# <function id="gtk_render_icon_pixbuf" />

[[function]]
id = "gtk_render_icon"

[[function]]
id = "gtk_render_icon_surface"

[extra]
body = '''

   function Get_Style_Context
      (Widget : not null access Gtk_Widget_Record'Class)
       return Gtk_Style_Context
   is
      function Internal (Widget : System.Address) return System.Address;
      pragma Import (C, Internal, "gtk_widget_get_style_context");
      Stub_Gtk_Style_Context : Gtk_Style_Context_Record;
   begin
      return Gtk_Style_Context
         (Get_User_Data (Internal (Get_Object (Widget)), Stub_Gtk_Style_Context));
   end Get_Style_Context;
       '''

[[extra.spec]]
text = '''

   function Get_Style_Context
      (Widget : not null access Gtk_Widget_Record'Class)
       return Gtk_Style_Context;
   --  Returns the style context associated to Widget.
   --  must not be freed.
       '''