# ============================================================
#   GtkSeparator
# ============================================================

[doc]
screenshot = "gtk-separator"
group = "Ornaments"

[[parameter]]
name = "self"
ada = "Separator"