# ============================================================
#   GtkStyle
# ============================================================

[[parameter]]
name = "self"
ada = "Style"

[[method]]
id = "gtk_style_get_valist"
bind = false
# va_list

[[method]]
id = "gtk_style_lookup_color"
return_as_param = "Found"

[[method]]
id = "gtk_style_render_icon"
bind = false
# need icon_source

[[method]]
id = "gtk_style_lookup_icon_set"
bind = false
# need icon_factory