# ============================================================
#   GtkTargetEntry
# ============================================================

[[parameter]]
name = "self"
ada = "Target_Entry"

[[record]]
ctype = "GtkTargetEntry"

[[record.field]]
name = "flags"
ctype = "GtkTargetFlags"

[[method]]
id = "gtk_target_entry_copy"
bind = false
# requires From_Object

[[method]]
id = "gtk_target_entry_new"

[[method.parameter]]
name = "Flags"
ctype = "GtkTargetFlags"