# ============================================================
#   GtkToolPalette
# ============================================================

[[enum]]
ctype = "GtkDestDefaults"

[[enum]]
ctype = "GtkToolPaletteDragTargets"

[[method]]
id = "gtk_tool_palette_get_hadjustment"
bind = false
# obsolete, use interface

[[method]]
id = "gtk_tool_palette_get_vadjustment"
bind = false
# obsolete, use interface