# ============================================================
#   GtkTextChildAnchor
# ============================================================

[[parameter]]
name = "self"
ada = "Anchor"

[[method]]
id = "gtk_text_child_anchor_get_widgets"
return = "WidgetSList"