# ============================================================
#   GtkToolItem
# ============================================================

[[parameter]]
name = "self"
ada = "Tool_Item"

[[method]]
id = "gtk_tool_item_retrieve_proxy_menu_item"
return = "GtkMenuItem"

[[method]]
id = "gtk_tool_item_get_proxy_menu_item"
return = "GtkMenuItem"

[[method]]
id = "gtk_tool_item_set_proxy_menu_item"

[[method.parameter]]
name = "menu_item"
ctype = "GtkMenuItem"