# ============================================================
#   GtkTreeModelFilter
# ============================================================
parent = "Gtk.Tree_Model.Gtk_Root_Tree_Model"

[[method]]
id = "gtk_tree_model_filter_new"
ada = "Gtk_New"

[[method.parameter]]
name = "root"
default = "Null_Gtk_Tree_Path"

[[method]]
id = "gtk_tree_model_filter_convert_child_iter_to_iter"
return = "void"

[[method]]
id = "gtk_tree_model_filter_set_modify_func"

[[method.parameter]]
name = "types"
type = "Glib.GType_Array"

[[method.parameter]]
name = "n_columns"
ada = ""
default = "Types'Length"