# ============================================================
#   GtkToolbar
# ============================================================

[[parameter]]
name = "self"
ada = "Toolbar"

[[method]]
id = "gtk_toolbar_set_show_arrow"

[[method.parameter]]
name = "show_arrow"
default = "True"

[[method]]
id = "gtk_toolbar_insert"

[[method.parameter]]
name = "pos"
default = "-1"

[[method]]
id = "gtk_tool_shell_get_orientation"
bind = false

[[method]]
id = "gtk_tool_shell_get_icon_size"
bind = false

[[method]]
id = "gtk_tool_shell_get_relief_style"
bind = false

[[method]]
id = "gtk_tool_shell_get_style"
bind = false