# ============================================================
#   GtkUIManager
# ============================================================

[[enum]]
ctype = "GtkUIManagerItemType"
ada = "Manager_Item_Type"
prefix = "GTK_UI_"

[[method]]
id = "gtk_ui_manager_add_ui"
ada = "Add_UI"

[[method.parameter]]
name = "type"
default = "Manager_Auto"

[[method.parameter]]
name = "top"
default = "False"

[[method]]
id = "gtk_ui_manager_remove_ui"
ada = "Remove_UI"

[[method]]
id = "gtk_ui_manager_add_ui_from_file"
ada = "Add_UI_From_File"

[[method.parameter]]
name = "error"
direction = "out"

[[method]]
id = "gtk_ui_manager_add_ui_from_resource"
ada = "Add_UI_From_Resource"

[[method.parameter]]
name = "error"
direction = "out"

[[method]]
id = "gtk_ui_manager_add_ui_from_string"
ada = "Add_UI_From_String"

[[method.parameter]]
name = "error"
direction = "out"

[[method.parameter]]
name = "length"
ada = ""
default = "-1"

[[method]]
id = "gtk_ui_manager_get_action_groups"
return = "ObjectList"

[[method]]
id = "gtk_ui_manager_get_toplevels"
return = "WidgetSList"