pragma Warnings (Off);
with Gtk.Dial;
with Gtk.Clock;
with Gnome.About;
with Gnome.App;
with Gnome.App_Bar;
with Gnome.App_Helper;
with Gnome.Client;
with Gnome.Color_Picker;
with Gnome.Date_Edit;
with Gnome.Dialog;
with Gnome.Dock;
with Gnome.Dock_Band;
with Gnome.Dock_Item;
with Gnome.Dock_Layout;
with Gnome.Druid;
with Gnome.Druid_Page;
with Gnome.Druid_Page_Finish;
with Gnome.Druid_Page_Standard;
with Gnome.Druid_Page_Start;
with Gnome.File_Entry;
with Gnome.Font_Picker;
with Gnome.GEntry;
with Gnome.HRef;
with Gnome.ICE;
with Gnome.Icon_Entry;
with Gnome.Icon_Selection;
with Gnome.Message_Box;
with Gnome.MDI;
with Gnome.MDI_Child;
with Gnome.MDI_Session;
with Gnome.Pixmap;
with Gnome.Pixmap_Entry;
with Gnome.Proc_Bar;
with Gnome.Property_Box;
with Gnome.Stock;
with Gnome.Scores;
with Gnome.UI_Defs;
with Gnome.Window;
pragma Warnings (On);

procedure Make_Gnome is
begin
   null;
end Make_Gnome;
