stages:
  - build

build:
  services:
     - image:gtk-deps
     - cpu:8
     - mem:16
  stage: build
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'pipeline'

  script:
    - generic_anod_ci
    - . /tmp/ci_env.sh

    # Build
    - anod build gtkada
