sudo: required
dist: xenial

language: generic
services:
 - docker

before_install:
 - docker pull ubuntu:16.04
 - contrib/travis.sh before_install

script:
 - docker build .
 - contrib/travis.sh script

deploy:
  on:
    branch:
      - master
  skip_cleanup: true
  provider: bintray
  file: contrib/bintray.json
  user: reznikmm
  key:
    secure: "ZnR4B9/5jrvjujFICLntJnnKvzLTpb+Th+ZluMzE1OVYeQjBfdgrxKEy4MPPxYxH4p24FyqKeuBRblccwQz7ukXjlUZ/qPcY6u2wgB9ZvYRVSLuen/nNlTtho6rHmk/aVeCPAzBlCVGatnbqwQpDbSM5E4eaEuNbAzVrORDnCZl3xnTXfY7yJRQttbs9bOoUj6Z5K//nJMlvR656wj6s1g3gqoKogx4X3YL42OIiu5LPeasDcOWorUy+RIeNwUqxXNrmUYLPdp/XpYqgwQNCkD2/qUvFO1dUq5m0lyR6zut2CaFhjWS6zNvpAhwDe5wlLsxdvOvCq43XtvgJUasPZ1WRyrMd+JLTw3Wa7xcEuVZQ1CQcCH8685NZKX3vg0nLwuqqMJgxRLVrtEyp+UDXalNEHL2EmUhTN1kk1HtwFQ/3PgkIzcm/0gh6PS6ZPU/oCrTslwz7m6tvpwTaPgYtYFgHux2rkUwO7dlZ1NOzxR43TrqgDELqgw3b1sblIgwwYNKd62tc1dkY12vem5e1vEGBv8qlzyw+dk5JAFov3Q0glYkH0Y2DuEqH9HfRQSnjoPHqG/JSoIP++s5i73CV3AR//dVVrrFoE881AgW2j2Up97t4XMcXRICCjS0y80v1Vm7F7F7ae86W8V+33MO7YMokFJGRmoyn5bE80P1gZ7o="

