# ============================================================
#   GCancellable
# ============================================================
ada = "Glib.Cancellable"

[[method]]
id = "g_cancellable_make_pollfd"
bind = false
# requires GPoll_FD