
# ============================================================
#   GCancellable
# ============================================================
[GCancellable]
  ada = "Glib.Cancellable"

  [[GCancellable.method]]
    id = "g_cancellable_make_pollfd"
    bind = false
    # requires GPoll_FD