# ============================================================
#   GdkClipboard
# ============================================================

[[method]]
id = "gdk_clipboard_set_valist"
bind = false
# varargs API

[[extra.with_body]]
pkg = "System"
use = false