# ============================================================
#   GdkCicpParams
# ============================================================
ada = "Gdk.Cicp_Params"
ada_access_root = true

[[enum]]
ctype = "GdkCicpRange"

[[extra.with_body]]
pkg = "System"
use = false
