# ============================================================
#   GdkDeviceTool
# ============================================================

[[enum]]
ctype = "GdkDeviceToolType"

[[enum]]
ctype = "GdkAxisFlags"

[[list]]
ctype = "GdkDeviceTool*"
ada   = "Device_Tool_List"

[[extra.with_spec]]
pkg = "System"
use = false
