# ============================================================
#   GdkDevice
# ============================================================

[[enum]]
ctype = "GdkInputSource"

[[method]]
id = "gdk_device_get_modifier_state"
bind = false
# No GdkModifierType binding

[[method]]
id = "gdk_device_get_seat"
bind = false
# No GdkSeat binding

[[method]]
id = "gdk_device_get_surface_at_position"
bind = false
# No GdkSurface binding

[[method]]
id = "::tool-changed"

[[method.parameter]]
name = "tool"
ctype = "GdkDeviceTool*"

[[extra.with_body]]
pkg = "System"
use = false