
# ============================================================
#   GdkDevice
# ============================================================
[GdkDevice]

  [[GdkDevice.enum]]
    ctype = "GdkDeviceType"

  [[GdkDevice.enum]]
    ctype = "GdkAxisFlags"

  [[GdkDevice.list]]
    ada = "Device_List"
    ctype = "GdkDevice"

  [[GdkDevice.method]]
    id = "::changed"
    bind = false
    # elaboration circularity

  [[GdkDevice.method]]
    id = "gdk_device_get_axis"
    bind = false
    # need support for array of gdoubles

  [[GdkDevice.method]]
    id = "gdk_device_get_axis_value"
    bind = false
    # need support for array of gdoubles

  [[GdkDevice.method]]
    id = "gdk_device_get_history"
    bind = false
    # need support for array of Gdk_Time_Coord

  [[GdkDevice.method]]
    id = "gdk_device_free_history"
    bind = false
    # no need while we don't bind get_history

  [[GdkDevice.method]]
    id = "gdk_device_grab_info_libgtk_only"
    bind = false
    # not part of library

  [[GdkDevice.method]]
    id = "gdk_device_get_key"
    bind = false
    return = ""
    # pending L118-010

  [[GdkDevice.method]]
    id = "gdk_device_get_window_at_position"
    bind = false
    # below

  [[GdkDevice.method]]
    id = "gdk_device_get_position"
    bind = false
    # pending resolution of a problem with generating the stub object

  [[GdkDevice.method]]
    id = "gdk_device_list_axes"
    bind = false
    # no support for atom lists

  [[GdkDevice.method]]
    id = "gdk_device_list_slave_devices"
    bind = false
    # no support for Gdk_Device_Type_Master lists

  [[GdkDevice.method]]
    id = "gdk_device_get_seat"
    return = "GObject*"

  [[GdkDevice.method]]
    id = "::tool-changed"

    [[GdkDevice.method.parameter]]
      name = "tool"
      ctype = "GObject*"

  [GdkDevice.extra]
    body = '''

   procedure Set_Source_Device
      (Event  : Gdk.Event.Gdk_Event;
       Device : not null access Gdk_Device_Record)
   is
      procedure Internal (Event : Gdk.Event.Gdk_Event; D : System.Address);
      pragma Import (C, Internal, "gdk_event_set_source_device");
   begin
      Internal (Event, Get_Object (Device));
   end Set_Source_Device;

   procedure Set_Device
      (Event  : Gdk.Event.Gdk_Event;
       Device : not null access Gdk_Device_Record)
   is
      procedure Internal (Event : Gdk.Event.Gdk_Event; D : System.Address);
      pragma Import (C, Internal, "gdk_event_set_device");
   begin
      Internal (Event, Get_Object (Device));
   end Set_Device;

   procedure Get_Window_At_Position
      (Self   : not null access Gdk_Device_Record;
       Win_X  : out Gint;
       Win_Y  : out Gint;
       Window : out Gdk.Gdk_Window)
   is
      function Internal
         (Self      : System.Address;
          Acc_Win_X : access Gint;
          Acc_Win_Y : access Gint) return Gdk.Gdk_Window;
      pragma Import (C, Internal, "gdk_device_get_window_at_position");
      Acc_Win_X  : aliased Gint;
      Acc_Win_Y  : aliased Gint;
   begin
      Window := Internal (Get_Object (Self), Acc_Win_X'Access, Acc_Win_Y'Access);
      Win_X := Acc_Win_X;
      Win_Y := Acc_Win_Y;
   end Get_Window_At_Position;
         '''

    [[GdkDevice.extra.spec]]
      text = '''

   procedure Get_Window_At_Position
      (Self   : not null access Gdk_Device_Record;
       Win_X  : out Gint;
       Win_Y  : out Gint;
       Window : out Gdk.Gdk_Window);
   --  Obtains the window underneath Device, returning the location of the
   --  device in Win_X and Win_Y. Returns null if the window tree under Device
   --  is not known to GDK (for example, belongs to another application).
   --  As a slave device coordinates are those of its master pointer, This
   --  function may not be called on devices of type
   --  Gdk.Device.Gdk_Device_Type_Slave, unless there is an ongoing grab on
   --  them, see Gdk.Device.Grab.
   --  Since: gtk+ 3.0
   --  "win_x": return location for the X coordinate of the device location,
   --  relative to the window origin, or null.
   --  "win_y": return location for the Y coordinate of the device location,
   --  relative to the window origin, or null.

   procedure Set_Device
      (Event   : Gdk.Event.Gdk_Event;
       Device  : not null access Gdk_Device_Record);
   --  Sets the device for Event to Device. The event must
   --  have been allocated by GTK+, for instance, by gdk_event_copy().

   procedure Set_Source_Device
      (Event   : Gdk.Event.Gdk_Event;
       Device  : not null access Gdk_Device_Record);
   --  Sets the slave device for Event to Device.
   --  The event must have been allocated by GTK+,
   --  for instance by gdk_event_copy().
         '''