# ============================================================
#   GdkDmabufTextureBuilder
# ============================================================
ada = "Gdk.Dmabuf_Texture_Builder"

[[extra.with_spec]]
pkg = "System"
use = false
