# ============================================================
#   GdkDmabufTexture
# ============================================================
ada = "Gdk.Dmabuf_Texture"

[[extra.with_body]]
pkg = "System"
use = false
