# ============================================================
#   GdkDisplay
# ============================================================

ada_access_root = true

[[method]]
id = "gdk_display_get_app_launch_context"
bind = false
# No GdkAppLaunchContext binding

[[method]]
id = "gdk_display_get_clipboard"
bind = false
# No GdkClipboard binding

[[method]]
id = "gdk_display_get_primary_clipboard"
bind = false
# No GdkClipboard binding

[[method]]
id = "gdk_display_create_gl_context"
bind = false
# No GdkGLContext binding

[[method]]
id = "gdk_display_get_monitor_at_surface"
bind = false
# No GdkMonitor binding

[[method]]
id = "gdk_display_get_default_seat"
bind = false
# No GdkSeat binding

[[method]]
id = "gdk_display_list_seats"
bind = false
# No GdkSeat binding

[[method]]
id = "gdk_display_map_keycode"
bind = false
# No array of GdkKeymapKey

[[method]]
id = "gdk_display_map_keyval"
bind = false
# No array of GdkKeymapKey

[[method]]
id = "gdk_display_translate_key"
bind = false
# No GdkModifierType binding

[[method]]
id = "::seat-added"
bind = false

[[method]]
id = "::seat-removed"
bind = false

[[method]]
id = "gdk_display_put_event"
bind = false
# No GdkEvent binding

[[extra.with_body]]
pkg = "System"
use = false