
# ============================================================
#   GdkDeviceTool
# ============================================================
[GdkDeviceTool]

  [[GdkDeviceTool.enum]]
    ctype = "GdkDeviceToolType"