# ============================================================
#   GdkDeviceTool
# ============================================================

[[enum]]
ctype = "GdkDeviceToolType"

[[enum]]
ctype = "GdkAxisFlags"

[[extra.with_body]]
pkg = "System"
use = false
