# ============================================================
#   GdkEnums
# ============================================================

[[enum]]
ctype = "GdkGravity"

[[enum]]
ctype = "GdkAnchorHints"
asbitfield = true