# ============================================================
#   GdkFrameClockPhase
# ============================================================

[[enum]]
ctype = "GdkFrameClockPhase"

[[extra.with_body]]
pkg = "System"
use = false