
# ============================================================
#   GdkFrameClock
# ============================================================
[GdkFrameClock]

  [[GdkFrameClock.enum]]
    ctype = "GdkFrameClockPhase"