# ============================================================
#   GdkGrabBrokenEvent
# ============================================================

[[extra.with_body]]
pkg = "Glib.Object"
use = true