# ============================================================
#   GdkMonitor
# ============================================================

[[enum]]
ctype = "GdkSubpixelLayout"

[[extra.with_body]]
pkg = "System"
use = false

[[extra.with_body]]
pkg = "Gdk.Display"
use = false