# ============================================================
#   GdkMemoryTexture
# ============================================================
ada = "Gdk.Memory_Texture"

[[extra.with_body]]
pkg = "System"
use = false
