# ============================================================
#   GdkMonitor
# ============================================================

[[enum]]
ctype = "GdkSubpixelLayout"

[[method]]
id = "gdk_monitor_get_display"
return = "GObject*"