# ============================================================
#   GdkPaintable
# ============================================================

[[enum]]
ctype = "GdkPaintableFlags"

[[extra.with_spec]]
pkg = "System"
use = false