
# ============================================================
#   GdkSeat
# ============================================================
[GdkSeat]

  [[GdkSeat.enum]]
    ctype = "GdkSeatCapabilities"

  [[GdkSeat.list]]
    ada = "Gdk_Seat_List"
    ctype = "GdkSeat*"

  [[GdkSeat.method]]
    id = "gdk_seat_get_slaves"
    return = "DeviceList"

  [[GdkSeat.method]]
    id = "gdk_seat_get_display"
    return = "GObject*"

  [[GdkSeat.method]]
    id = "::tool-added"

    [[GdkSeat.method.parameter]]
      name = "tool"
      ctype = "GObject*"

  [[GdkSeat.method]]
    id = "::tool-removed"

    [[GdkSeat.method.parameter]]
      name = "tool"
      ctype = "GObject*"

  [[GdkSeat.method]]
    id = "::device-added"

    [[GdkSeat.method.parameter]]
      name = "device"
      ctype = "GObject*"

  [[GdkSeat.method]]
    id = "::device-removed"

    [[GdkSeat.method.parameter]]
      name = "device"
      ctype = "GObject*"

  [GdkSeat.extra]

    [[GdkSeat.extra.with_spec]]
      pkg = "Gdk.Types"