# ============================================================
#   GdkTouchpadEvent
# ============================================================

[[enum]]
ctype = "GdkTouchpadGesturePhase"
prefix = "GDK_TOUCHPAD_GESTURE_"