
# ============================================================
#   GIcon
# ============================================================
[GIcon]
  ada = "Glib.G_Icon"

  [[GIcon.virtual_method]]
    id = "*"
    bind = false

  [[GIcon.method]]
    id = "g_icon_hash"

    [[GIcon.method.parameter]]
      name = "icon"
      type = "G_Icon"