
# ============================================================
#   GIOChannel
# ============================================================
[GIOChannel]
  ada = "Glib.IOChannel"

  [[GIOChannel.enum]]
    ctype = "GIOCondition"

  [[GIOChannel.enum]]
    ctype = "GIOFlags"

  [[GIOChannel.enum]]
    ctype = "GIOStatus"

  [[GIOChannel.enum]]
    ctype = "GIOError"

  [[GIOChannel.enum]]
    ctype = "GIOChannelError"

  [[GIOChannel.enum]]
    ctype = "GSeekType"

  [[GIOChannel.record]]
    ctype = "GIOFuncs"

  [[GIOChannel.record]]
    ctype = "GIOChannel"
    ada = "GIO_Channel_Record"

  [[GIOChannel.method]]
    id = "g_io_channel_new_file"
    bind = false

  [[GIOChannel.method]]
    id = "g_io_channel_read_line"
    bind = false
    # too complicated for generator

  [[GIOChannel.method]]
    id = "g_io_channel_read_to_end"
    bind = false
    # too complicated for generator

  [[GIOChannel.method]]
    id = "g_io_channel_get_type"
    bind = false
    # exists only in gir file

  [[GIOChannel.method]]
    id = "g_io_channel_shutdown"
    bind = false
    # gir file should be updated

  [[GIOChannel.method]]
    id = "g_io_channel_flush"
    bind = false
    # gir file should be updated

  [[GIOChannel.method]]
    id = "g_io_channel_set_encoding"
    bind = false
    # gir file should be updated

  [[GIOChannel.method]]
    id = "g_io_channel_set_flags"
    bind = false
    # gir file should be updated

  [[GIOChannel.method]]
    id = "g_io_channel_read_chars"
    bind = false
    # gir file should be updated

  [[GIOChannel.method]]
    id = "g_io_channel_read_line_string"
    bind = false
    # gir file should be updated

  [[GIOChannel.method]]
    id = "g_io_channel_read_unichar"
    bind = false
    # gir file should be updated

  [[GIOChannel.method]]
    id = "g_io_channel_write_unichar"
    bind = false
    # gir file should be updated

  [[GIOChannel.method]]
    id = "g_io_channel_write_chars"
    bind = false
    # gir file should be updated
    # deprecated methods

  [[GIOChannel.method]]
    id = "g_io_channel_close"
    bind = false

  [[GIOChannel.method]]
    id = "g_io_channel_read"
    bind = false

  [[GIOChannel.method]]
    id = "g_io_channel_seek"
    bind = false

  [[GIOChannel.method]]
    id = "g_io_channel_write"
    bind = false

  [[GIOChannel.function]]
    id = "g_io_create_watch"

  [GIOChannel.extra]
    body = '''

   ------------------
   -- Set_Encoding --
   ------------------

   function Set_Encoding
      (Self     : Giochannel;
       Encoding : UTF8_String := "";
       Error    : access Glib.Error.GError) return GIOStatus
   is
      function Internal
         (Self     : Giochannel;
          Encoding : Gtkada.Types.Chars_Ptr;
          Error    : access Glib.Error.GError) return GIOStatus;
      pragma Import (C, Internal, "g_io_channel_set_encoding");
      Tmp_Encoding : Gtkada.Types.Chars_Ptr;
      Tmp_Return   : GIOStatus;
   begin
      if Encoding = "" then
         Tmp_Encoding := Gtkada.Types.Null_Ptr;
      else
         Tmp_Encoding := New_String (Encoding);
      end if;
      Tmp_Return := Internal (Self, Tmp_Encoding, Error);
      Free (Tmp_Encoding);
      return Tmp_Return;
   end Set_Encoding;

   ----------------
   -- Read_Chars --
   ----------------

   function Read_Chars
      (Self       : Giochannel;
       Buf        : out Ada.Streams.Stream_Element_Array;
       Bytes_Read : access Gsize;
       Error    : access Glib.Error.GError) return GIOStatus
   is
      function Internal
         (Self           : Giochannel;
          Buf            : System.Address;
          Count          : Gsize;
          Acc_Bytes_Read : access Gsize;
          Error          : access Glib.Error.GError) return GIOStatus;
      pragma Import (C, Internal, "g_io_channel_read_chars");
      Acc_Bytes_Read : aliased Gsize;
      Tmp_Return     : GIOStatus;
   begin
      Tmp_Return := Internal (Self, Buf'Address, Buf'Length, Acc_Bytes_Read'Access, Error);
      if Bytes_Read /= null then
         Bytes_Read.all := Acc_Bytes_Read;
      end if;
      return Tmp_Return;
   end Read_Chars;

   -----------------
   -- Write_Chars --
   -----------------

   function Write_Chars
      (Self          : Giochannel;
       Buf           : Ada.Streams.Stream_Element_Array;
       Bytes_Written : access Gsize;
       Error         : access Glib.Error.GError) return GIOStatus
   is
      function Internal
         (Self              : Giochannel;
          Buf               : System.Address;
          Count             : Gssize;
          Acc_Bytes_Written : access Gsize;
          Error             : access Glib.Error.GError) return GIOStatus;
      pragma Import (C, Internal, "g_io_channel_write_chars");
      Acc_Bytes_Written : aliased Gsize;
      Tmp_Return        : GIOStatus;
   begin
      Tmp_Return := Internal (Self, Buf'Address, Buf'Length, Acc_Bytes_Written'Access, Error);
      Bytes_Written.all := Acc_Bytes_Written;
      return Tmp_Return;
   end Write_Chars;

       '''

    [[GIOChannel.extra.with_spec]]
      pkg = "Glib.Error"

    [[GIOChannel.extra.with_spec]]
      pkg = "Ada.Streams"

    [[GIOChannel.extra.spec]]
      text = '''

   function Shutdown
     (Self     : Giochannel;
      Flush    : Glib.Gboolean;
      Error    : access Glib.Error.GError) return GIOStatus;
   pragma Import (C, Shutdown, "g_io_channel_shutdown");
   --  Close an IO channel. Any pending data to be written will be flushed if
   --  Flush is True. The channel will not be freed until the last reference is
   --  dropped using Glib.IOChannel.Unref.
   --  "flush": if True, flush pending

   function Flush
     (Self  : Giochannel;
      Error : access Glib.Error.GError) return GIOStatus;
   pragma Import (C, Flush, "g_io_channel_flush");
   --  Flushes the write buffer for the GIOChannel.

   function Set_Encoding
      (Self     : Giochannel;
       Encoding : UTF8_String := "";
       Error    : access Glib.Error.GError) return GIOStatus;
   --  Sets the encoding for the input/output of the channel. The internal
   --  encoding is always UTF-8. The default encoding for the external file is
   --  UTF-8.
   --  The encoding null is safe to use with binary data.
   --  The encoding can only be set if one of the following conditions is
   --  true:
   --  - The channel was just created, and has not been written to or read
   --  from yet.
   --  - The channel is write-only.
   --  - The channel is a file, and the file pointer was just repositioned by
   --  a call to Glib.IOChannel.Seek_Position. (This flushes all the internal
   --  buffers.)
   --  - The current encoding is null or UTF-8.
   --  - One of the (new API) read functions has just returned
   --  Glib.IOChannel.G_Io_Status_Eof (or, in the case of
   --  g_io_channel_read_to_end, Glib.IOChannel.G_Io_Status_Normal).
   --  - One of the functions Glib.IOChannel.Read_Chars or
   --  Glib.IOChannel.Read_Unichar has returned
   --  Glib.IOChannel.G_Io_Status_Again or Glib.IOChannel.G_Io_Status_Error.
   --  This may be useful in the case of G_CONVERT_ERROR_ILLEGAL_SEQUENCE.
   --  Returning one of these statuses from g_io_channel_read_line,
   --  Glib.IOChannel.Read_Line_String, or g_io_channel_read_to_end does not
   --  guarantee that the encoding can be changed.
   --  Channels which do not meet one of the above conditions cannot call
   --  Glib.IOChannel.Seek_Position with an offset of
   --  Glib.IOChannel.G_Seek_Cur, and, if they are "seekable", cannot call
   --  Glib.IOChannel.Write_Chars after calling one of the API "read"
   --  functions.
   --  "encoding": the encoding type

   function Set_Flags
     (Self : Giochannel;
     Flags : GIOFlags;
     Error : access Glib.Error.GError) return GIOStatus;
   pragma Import (C, Set_Flags, "g_io_channel_set_flags");
   --  Sets the (writeable) flags in Channel to (Flags and
   --  Glib.IOChannel.G_Io_Flag_Set_Mask).
   --  "flags": the flags to set on the IO channel

   function Read_Chars
      (Self       : Giochannel;
       Buf        : out Ada.Streams.Stream_Element_Array;
       Bytes_Read : access Gsize;
       Error      : access Glib.Error.GError) return GIOStatus;
   --  Replacement for g_io_channel_read with the new API.
   --  "buf": a buffer to read data into
   --  "count": is sent as Buf'Length.
   --  "bytes_read": The number of bytes read. This may be zero even on
   --  success if count less than 6 and the channel's encoding is non-null.
   --  This indicates that the next UTF-8 character is too wide for
   --  the buffer.

   function Write_Chars
      (Self          : Giochannel;
       Buf           : Ada.Streams.Stream_Element_Array;
       Bytes_Written : access Gsize;
       Error         : access Glib.Error.GError) return GIOStatus;
   --  Replacement for g_io_channel_write with the new API.
   --  On seekable channels with encodings other than null or UTF-8, generic
   --  mixing of reading and writing is not allowed. A call to
   --  g_io_channel_write_chars () may only be made on a channel from which
   --  data has been read in the cases described in the documentation for
   --  g_io_channel_set_encoding ().
   --  "buf": a buffer to write data from
   --  "count": is sent as Buf'Length.
   --  "bytes_written": The number of bytes written. This can be nonzero even
   --  if the return value is not Glib.IOChannel.G_Io_Status_Normal. If the
   --  return value is Glib.IOChannel.G_Io_Status_Normal and the channel is
   --  blocking, this will always be equal to Count if Count >= 0.

   function Read_Line_String
      (Self           : Giochannel;
       Buffer         : Glib.String.Gstring;
       Terminator_Pos : in out Gsize;
       Error          : access Glib.Error.GError) return GIOStatus;
   pragma Import (C, Read_Line_String, "g_io_channel_read_line_string");
   --  Reads a line from a Glib.IOChannel.Giochannel, using a
   --  Glib.String.Gstring as a buffer.
   --  "buffer": a Glib.String.Gstring into which the line will be written. If
   --  Buffer already contains data, the old data will be overwritten.
   --  "terminator_pos": location to store position of line terminator, or
   --  null

   function Read_Unichar
      (Self    : Giochannel;
       Thechar : access Gunichar;
       Error   : access Glib.Error.GError) return GIOStatus;
   pragma Import (C, Read_Unichar, "g_io_channel_read_unichar");
   --  Reads a Unicode character from Channel. This function cannot be called
   --  on a channel with null encoding.
   --  "thechar": a location to return a character

   function Write_Unichar
      (Self    : Giochannel;
       Thechar : Gunichar;
       Error   : access Glib.Error.GError) return GIOStatus;
   pragma Import (C, Write_Unichar, "g_io_channel_write_unichar");
   --  Writes a Unicode character to Channel. This function cannot be called
   --  on a channel with null encoding.
   --  "thechar": a character

   generic
      type User_Data is limited private;
   function Generic_Add_Watch
     (Channel    : Giochannel;
      Condition  : GIOCondition;
      Callback   : access function
         (Source    : Giochannel;
          Condition : GIOCondition;
          Data      : access User_Data) return Glib.Gboolean;
      Data       : access User_Data) return Glib.Main.G_Source_Id;
   pragma Import (C, Generic_Add_Watch, "g_io_add_watch");
   --  Adds the Glib.IOChannel.Giochannel into the default main loop context
   --  with the default priority.
   --  "channel": a Glib.IOChannel.Giochannel
   --  "condition": the condition to watch for
   --  "callback": the function to call when the condition is satisfied
       '''

    [[GIOChannel.extra.type]]
      ctype = "GIOChannel*"
      ada = "Giochannel"
      text = '''

           type Giochannel is access all GIO_Channel_Record;
           pragma No_Strict_Aliasing (Giochannel);
         '''