# ============================================================
#   GIOStream
# ============================================================

ada = "Glib.IO_Stream"

[[enum]]
ctype = "GIOStreamSpliceFlags"
