# ============================================================
#   GMenu
# ============================================================
ada = "Glib.Menu"

[[method]]
id = "g_menu_get_type"
ada = "Get_Type_Menu"