
# ============================================================
#   GMenu
# ============================================================
[GMenu]
  ada = "Glib.Menu"

  [[GMenu.method]]
    id = "g_menu_get_type"
    ada = "Get_Type_Menu"