# ============================================================
#   GNotification
# ============================================================
ada = "Glib.Notification"

[[method]]
id = "g_notification_set_body"

[[method.parameter]]
name = "body"
ada = "the_body"

[[enum]]
ctype = "GNotificationPriority"