
# ============================================================
#   GNotification
# ============================================================
[GNotification]
  ada = "Glib.Notification"

  [[GNotification.method]]
    id = "g_notification_set_body"

    [[GNotification.method.parameter]]
      name = "body"
      ada = "the_body"

  [[GNotification.enum]]
    ctype = "GNotificationPriority"