
# ============================================================
#   GPoll
# ============================================================
[GPoll]
  ada = "Glib.Poll"

  [[GPoll.record]]
    ctype = "GPollFD"