# ============================================================
#   Graphene_Size_T
# ============================================================

ada = "Graphene.Size"

[[method]]
id = "graphene_size_alloc"
bind = false