# ============================================================
#   GString
# ============================================================
ada = "Glib.String"

[[record]]
ctype = "GString"

[[method]]
id = "g_string_append_vprintf"
bind = false
# valist

[[method]]
id = "g_string_vprintf"
bind = false
# valist

[[method]]
id = "g_string_free_to_bytes"
bind = false
# requires GByte