# ============================================================
#   GString
# ============================================================
ada = "Glib.String"

[[extra.type]]
ctype = "GString*"
ada = "Gstring"
text = '''type Gstring is access all Gstring_Record;
'''

[[record]]
ctype = "GString"
ada = "Gstring_Record"

[[method]]
id = "g_string_append_vprintf"
bind = false
# valist

[[method]]
id = "g_string_vprintf"
bind = false
# valist

[[method]]
id = "g_string_free_to_bytes"
bind = false
# requires GByte

[[method]]
id = "g_string_append_c"
ada = "Append_Char"
[[method]]
id = "g_string_prepend_c"
ada = "Prepend_Char"
