
# ============================================================
#   GtkAlignment
# ============================================================
[GtkAlignment]

  [GtkAlignment.doc]
    screenshot = "gtk-alignment"
    testgtk = "create_alignment.adb"

  [[GtkAlignment.parameter]]
    name = "self"
    ada = "Alignment"

  [[GtkAlignment.method]]
    id = "gtkada_GtkAlignment_get_xalign"

  [[GtkAlignment.method]]
    id = "gtkada_GtkAlignment_get_xscale"

  [[GtkAlignment.method]]
    id = "gtkada_GtkAlignment_get_yalign"

  [[GtkAlignment.method]]
    id = "gtkada_GtkAlignment_get_yscale"