
# ============================================================
#   GtkAccelGroup
# ============================================================
[GtkAccelGroup]

  [[GtkAccelGroup.parameter]]
    name = "self"
    ada = "Accel_Group"

  [[GtkAccelGroup.method]]
    id = "gtk_accel_group_new"

    [GtkAccelGroup.method.doc]
      text = '''
Creates a new Gtk.Accel_Group.Gtk_Accel_Group.
Remember to call Gtk.Window.Add_Accel_Group to active the group.'''

  [[GtkAccelGroup.method]]
    id = "gtk_accel_group_connect"

    [[GtkAccelGroup.method.parameter]]
      name = "closure"
      type = "C_Gtk_Accel_Group_Activate"

  [[GtkAccelGroup.method]]
    id = "gtk_accel_group_disconnect"

    [[GtkAccelGroup.method.parameter]]
      name = "closure"
      type = "C_Gtk_Accel_Group_Activate"

  [[GtkAccelGroup.method]]
    id = "gtk_accel_group_connect_by_path"

    [[GtkAccelGroup.method.parameter]]
      name = "closure"
      type = "C_Gtk_Accel_Group_Activate"

  [[GtkAccelGroup.method]]
    id = "gtk_accel_group_query"
    bind = false
    # ???Would be nice

  [[GtkAccelGroup.method]]
    id = "gtk_accel_group_from_accel_closure"

    [[GtkAccelGroup.method.parameter]]
      name = "closure"
      type = "C_Gtk_Accel_Group_Activate"

  [[GtkAccelGroup.function]]
    id = "gtk_accel_groups_activate"

    [[GtkAccelGroup.function.parameter]]
      name = "accel_key"
      type = "Gdk.Types.Gdk_Key_Type"

  [[GtkAccelGroup.function]]
    id = "gtk_accel_groups_from_object"
    ada = "From_Object"
    return = "ObjectSList"

  [[GtkAccelGroup.function]]
    id = "gtk_accelerator_valid"

    [[GtkAccelGroup.function.parameter]]
      name = "keyval"
      type = "Gdk.Types.Gdk_Key_Type"

  [[GtkAccelGroup.function]]
    id = "gtk_accelerator_parse"

    [[GtkAccelGroup.function.parameter]]
      name = "accelerator_key"
      ctype = "GdkKeyType*"

  [[GtkAccelGroup.function]]
    id = "gtk_accelerator_name"

    [[GtkAccelGroup.function.parameter]]
      name = "accelerator_key"
      type = "Gdk.Types.Gdk_Key_Type"

  [[GtkAccelGroup.function]]
    id = "gtk_accelerator_get_label"

    [[GtkAccelGroup.function.parameter]]
      name = "accelerator_key"
      type = "Gdk.Types.Gdk_Key_Type"

  [[GtkAccelGroup.function]]
    id = "gtk_accelerator_set_default_mod_mask"
    ada = "Set_Default_Mod_Mask"

  [[GtkAccelGroup.function]]
    id = "gtk_accelerator_get_default_mod_mask"
    ada = "Get_Default_Mod_Mask"
    return = "GdkModifierType"

  [[GtkAccelGroup.enum]]
    ctype = "GtkAccelFlags"
    prefix = "GTK_"

  [[GtkAccelGroup.record]]
    ctype = "GtkAccelKey"

    [[GtkAccelGroup.record.field]]
      name = "accel_key"
      ctype = "GdkKeyType"

    [[GtkAccelGroup.record.field]]
      name = "accel_flags"
      ctype = "GtkAccelFlags"

  [GtkAccelGroup.extra]

    [[GtkAccelGroup.extra.type]]
      ctype = "GtkAccelGroupActive"
      ada = "Gtk_Accel_Group_Activate"
      text = '''

   type Gtk_Accel_Group_Activate is access function
     (Accel_Group   : access Gtk_Accel_Group_Record'Class;
      Acceleratable : Glib.Object.GObject;
      Keyval        : Gdk.Types.Gdk_Key_Type;
      Modifier      : Gdk.Types.Gdk_Modifier_Type) return Boolean;

   type C_Gtk_Accel_Group_Activate is access function
     (Accel_Group   : System.Address;
      Acceleratable : System.Address;
      Keyval        : Gdk.Types.Gdk_Key_Type;
      Modifier      : Gdk.Types.Gdk_Modifier_Type) return Boolean;
   pragma Convention (C, C_Gtk_Accel_Group_Activate);
   --  Same as Gtk_Accel_Group_Activate, but passing directly the C values.
   --  You must use Get_User_Data to convert to the Ada types.
        '''