
# ============================================================
#   GtkAccelLabel
# ============================================================
[GtkAccelLabel]

  [[GtkAccelLabel.parameter]]
    name = "self"
    ada = "Accel_Label"