
# ============================================================
#   GtkBin
# ============================================================
[GtkBin]

  [GtkBin.doc]
    group = "Abstract base classes"

  [[GtkBin.parameter]]
    name = "self"
    ada = "Bin"