
# ============================================================
#   GtkBuildable
# ============================================================
[GtkBuildable]

  [[GtkBuildable.virtual_method]]
    id = "*"
    bind = false

  [[GtkBuildable.method]]
    id = "gtk_buildable_custom_tag_start"
    bind = false