
# ============================================================
#   GtkCellView
# ============================================================
[GtkCellView]

  [[GtkCellView.parameter]]
    name = "self"
    ada = "Cell_View"