
# ============================================================
#   GtkCalendar
# ============================================================
[GtkCalendar]

  [GtkCalendar.doc]
    screenshot = "gtk-calendar"
    group = "Selectors"
    testgtk = "create_calendar.adb"

  [[GtkCalendar.parameter]]
    name = "self"
    ada = "Calendar"

  [[GtkCalendar.enum]]
    ctype = "GtkCalendarDisplayOptions"
    prefix = "GTK_CALENDAR_"