# ============================================================
#   GtkContainer
# ============================================================

[[parameter]]
name = "self"
ada = "Container"

[[method]]
id = "gtk_container_add_with_properties"
bind = false
# varargs

[[method]]
id = "gtk_container_child_get"
bind = false
# varargs

[[method]]
id = "gtk_container_child_get_valist"
bind = false
# varargs

[[method]]
id = "gtk_container_child_set"
bind = false
# varargs

[[method]]
id = "gtk_container_child_set_valist"
bind = false
# varargs

[[method]]
id = "gtk_container_get_children"
return = "WidgetList"

[[method]]
id = "gtk_container_set_focus_chain"

[[method.parameter]]
name = "focusable_widgets"
ctype = "WidgetList"

[[method]]
id = "gtk_container_child_set_property"

[[method.parameter]]
name = "value"
ctype = "GValue"
direction = "in"
# ??? Binding needs testing

[[method]]
id = "gtk_container_get_focus_chain"
bind = false
return_as_param = "Success"

[[method.parameter]]
name = "focusable_widgets"
ctype = "WidgetList*"
direction = "out"