# ============================================================
#   GtkColumnViewColumn
# ============================================================

[extra]

# Gtk.Column_View withs Gtk.Column_View_Column, so the full view can only
# be had in the body.
[[extra.with_spec]]
pkg = "Gtk.Column_View"
limited = true

[[extra.with_body]]
pkg = "Gtk.Column_View"
