
# ============================================================
#   GtkComboBoxText
# ============================================================
[GtkComboBoxText]

  [GtkComboBoxText.doc]
    group = "Numeric/Text Data Entry"