# ============================================================
#   GtkCellRenderer
# ============================================================

[doc]
group = "Trees and Lists"

[[parameter]]
name = "self"
ada  = "Cell"

[[enum]]
ctype = "GtkCellRendererState"

[[enum]]
ctype = "GtkCellRendererMode"

[[list]]
ada   = "Cell_Renderer_List"
ctype = "GtkCellRenderer"
