
# ============================================================
#   GtkCellRenderer
# ============================================================
[GtkCellRenderer]

  [[GtkCellRenderer.parameter]]
    name = "self"
    ada = "Cell"

  [[GtkCellRenderer.enum]]
    ctype = "GtkCellRendererState"

  [[GtkCellRenderer.enum]]
    ctype = "GtkCellRendererMode"

  [[GtkCellRenderer.method]]
    id = "gtk_cell_renderer_get_size"

    [[GtkCellRenderer.method.parameter]]
      name = "cell_area"
      ctype = "GdkRectangle**"

  [[GtkCellRenderer.list]]
    ada = "Cell_Renderer_List"
    ctype = "GtkCellRenderer"