
# ============================================================
#   GtkCssSection
# ============================================================
[GtkCssSection]

  [[GtkCssSection.enum]]
    ctype = "GtkCssSectionType"

  [[GtkCssSection.method]]
    id = "gtk_css_section_get_file"
    bind = false
    # needs GFile