# ============================================================
#   GtkColorButton
# ============================================================

[doc]
group = "Buttons and Toggles"

[[parameter]]
name = "self"
ada = "Button"

[[method]]
id = "gtk_color_button_get_rgba"
bind = false
# from interface now

[[method]]
id = "gtk_color_button_set_rgba"
bind = false
# from interface now

[[method]]
id = "gtk_color_button_get_use_alpha"
bind = false
# from interface now

[[method]]
id = "gtk_color_button_set_use_alpha"
bind = false
# from interface now