# ============================================================
#   GtkDragSource
# ============================================================

[doc]
group       = "Drag and Drop"
gtkada_demo = "create_drag_and_drop.adb"
