# ============================================================
#   GtkEventControllerScroll
# ============================================================

[[enum]]
ctype = "GtkEventControllerScrollFlags"
asbitfield = true