
# ============================================================
#   GtkExpander
# ============================================================
[GtkExpander]

  [GtkExpander.doc]
    screenshot = "gtk-expanded"
    group = "Layout containers"

  [[GtkExpander.parameter]]
    name = "self"
    ada = "Expander"