
# ============================================================
#   GtkEditable
# ============================================================
[GtkEditable]

  [[GtkEditable.parameter]]
    name = "self"
    ada = "Editable"

  [[GtkEditable.method]]
    id = "::insert-text"

    [[GtkEditable.method.parameter]]
      name = "position"
      direction = "access"

  [[GtkEditable.method]]
    id = "gtk_editable_select_region"

    [[GtkEditable.method.parameter]]
      name = "end_pos"
      default = "-1"

  [[GtkEditable.method]]
    id = "gtk_editable_delete_text"

    [[GtkEditable.method.parameter]]
      name = "end_pos"
      default = "-1"

  [[GtkEditable.method]]
    id = "gtk_editable_get_chars"

    [[GtkEditable.method.parameter]]
      name = "end_pos"
      default = "-1"

  [GtkEditable.extra]
    body = '''

   procedure Insert_Text
     (Editable : Gtk_Editable;
      New_Text : UTF8_String;
      Position : in out Gint) is
   begin
      Insert_Text
        (Editable, New_Text & ASCII.NUL, New_Text'Length, Position);
   end Insert_Text;
        '''

    [[GtkEditable.extra.spec]]
      text = '''

   procedure Insert_Text
     (Editable : Gtk_Editable;
      New_Text : UTF8_String;
      Position : in out Gint);
   --  Convenience subprogram, identical to Insert_Text above without
   --  the requirement to supply the New_Text_Length argument.
        '''

  [[GtkEditable.method]]
    id = "gtk_editable_get_selection_bounds"
    return_as_param = "Has_Selection"