# ============================================================
#   GtkExpander
# ============================================================

[doc]
screenshot = "gtk-expander"
group = "Layout containers"
