# ============================================================
#   GtkExpander
# ============================================================

[doc]
screenshot = "gtk-expanded"
group = "Layout containers"
