# ============================================================
#   GtkFileChooser
# ============================================================

[doc]
group = ""

[[parameter]]
name = "self"
ada = "Chooser"

[[enum]]
ctype = "GtkFileChooserAction"
prefix = "GTK_FILE_CHOOSER_"

[[enum]]
ctype = "GtkFileChooserConfirmation"
prefix = "GTK_FILE_CHOOSER_"

[[enum]]
ctype = "GtkFileChooserError"
prefix = "GTK_FILE_CHOOSER_"
# we won't bind any of these internal functions which pass GFile types

[[method]]
id = "gtk_file_chooser_get_file"
bind = false

[[method]]
id = "gtk_file_chooser_get_files"
bind = false

[[method]]
id = "gtk_file_chooser_get_current_folder_file"
bind = false

[[method]]
id = "gtk_file_chooser_get_preview_file"
bind = false

[[method]]
id = "gtk_file_chooser_select_file"
bind = false

[[method]]
id = "gtk_file_chooser_set_current_folder_file"
bind = false

[[method]]
id = "gtk_file_chooser_set_file"
bind = false

[[method]]
id = "gtk_file_chooser_unselect_file"
bind = false

[[method]]
id = "gtk_file_chooser_get_filenames"
return = "StringSList"

[[method]]
id = "gtk_file_chooser_get_uris"
return = "StringSList"

[[method]]
id = "gtk_file_chooser_list_shortcut_folder_uris"
return = "StringSList"

[[method]]
id = "gtk_file_chooser_list_shortcut_folders"
return = "StringSList"

[[method]]
id = "gtk_file_chooser_list_filters"
return = "ObjectSList"