
# ============================================================
#   GtkFlowBox
# ============================================================
[GtkFlowBox]

  [[GtkFlowBox.method]]
    id = "gtk_flow_box_get_selected_children"
    return = "WidgetList"