
# ============================================================
#   GtkFileChooserButton
# ============================================================
[GtkFileChooserButton]

  [GtkFileChooserButton.doc]
    group = "Buttons and Toggles"

  [[GtkFileChooserButton.parameter]]
    name = "self"
    ada = "Button"