# ============================================================
#   GtkFileFilter
# ============================================================

[[enum]]
ctype = "GtkFileFilterFlags"

[[record]]
ctype = "GtkFileFilterInfo"