
# ============================================================
#   GtkFontButton
# ============================================================
[GtkFontButton]

  [[GtkFontButton.parameter]]
    name = "self"
    ada = "Font_Button"