# ============================================================
#   GtkFilter
# ============================================================

[[enum]]
ctype = "GtkFilterChange"
prefix = "GTK_FILTER_CHANGE_"

[[enum]]
ctype = "GtkFilterMatch"
prefix = "GTK_FILTER_"

[[method]]
id = "gtk_filter_match"

[[method.parameter]]
name = "item"
ctype = "GObject*"

[extra]
body = '''

   function Unchecked_To_Gtk_Filter_Change is new
     Glib.Values.Unsafe_Enum_Nth (Gtk_Filter_Change);
       '''
