# ============================================================
#   GtkFlowBoxChild
# ============================================================

[[list]]
ada = "Flow_Box_Child_List"
ctype = "GtkFlowBoxChild"
