
# ============================================================
#   GtkFontChooser
# ============================================================
[GtkFontChooser]

  [[GtkFontChooser.enum]]
    ctype = "GtkFontChooserLevel"