
# ============================================================
#   GtkFileFilter
# ============================================================
[GtkFileFilter]

  [[GtkFileFilter.enum]]
    ctype = "GtkFileFilterFlags"

  [[GtkFileFilter.record]]
    ctype = "GtkFileFilterInfo"