
# ============================================================
#   GtkHButtonBox
# ============================================================
[GtkHButtonBox]

  [GtkHButtonBox.doc]
    group = "Layout containers"
    text = '''
A Gtk_Hbutton_Box is a specific Gtk_Button_Box that organizes its
children horizontally.
The beginning of the box (when you add children with Gtk.Box.Pack_Start)
is on the left of the box. Its end (for Gtk.Box.Pack_End) is on the right.
      '''

  [[GtkHButtonBox.parameter]]
    name = "self"
    ada = "Widget"