# ============================================================
#   GtkHSeparator
# ============================================================
into = "GtkSeparator"

[[type]]
name = "Gtk_Hseparator"
subtype = true

[[method]]
id = "gtk_hseparator_new"
ada = "Gtk_New_Hseparator"

[[parameter]]
name = "self"
ada = "Separator"

[[method]]
id = "gtk_hseparator_get_type"
ada = "Hseparator_Get_Type"