
# ============================================================
#   GtkHandleBox
# ============================================================
[GtkHandleBox]
  obsolescent = true

  [[GtkHandleBox.parameter]]
    name = "self"
    ada = "Handle_Box"