# ============================================================
#   GtkHeaderBar
# ============================================================

[doc]
group       = "Layout containers"
gtkada_demo = "create_header_bar.adb"
