# ============================================================
#   GtkHRuler
# ============================================================
into = "GtkRuler"

[[type]]
name = "Gtk_Hruler"
subtype = true

[[method]]
id = "gtk_hruler_new"
ada = "Gtk_New_Hruler"

[[parameter]]
name = "self"
ada = "Ruler"

[[method]]
id = "gtk_hruler_get_type"
ada = "Hruler_Get_Type"