# ============================================================
#   GtkHBox
# ============================================================
into = "GtkBox"

[[type]]
name = "Gtk_Hbox"
subtype = true

[[method]]
id = "gtk_hbox_new"
ada = "Gtk_New_Hbox"

[[method.parameter]]
name = "homogeneous"
default = "False"

[[method.parameter]]
name = "spacing"
default = "0"

[[parameter]]
name = "self"
ada = "Box"

[[method]]
id = "gtk_hbox_get_type"
ada = "Get_Hbox_Type"