
# ============================================================
#   GtkImage
# ============================================================
[GtkImage]

  [GtkImage.doc]
    screenshot = "gtk-image"
    group = "Display widgets"

  [[GtkImage.parameter]]
    name = "self"
    ada = "Image"

  [[GtkImage.parameter]]
    name = "image"
    ada = "Val"

  [[GtkImage.parameter]]
    name = "size"
    type = "Gtk.Enums.Gtk_Icon_Size"

  [[GtkImage.method]]
    id = "gtk_image_new_from_animation"
    ada = "Gtk_New"

  [[GtkImage.method]]
    id = "gtk_image_new_from_file"
    ada = "Gtk_New"

  [[GtkImage.method]]
    id = "gtk_image_new_from_image"
    ada = "Gtk_New"

  [[GtkImage.method]]
    id = "gtk_image_new_from_pixbuf"
    ada = "Gtk_New"

  [[GtkImage.method]]
    id = "gtk_image_new_from_icon_set"
    ada = "Gtk_New"

  [[GtkImage.method]]
    id = "gtk_image_new_from_pixmap"
    ada = "Gtk_New"

  [[GtkImage.method]]
    id = "gtk_image_new_from_stock"
    ada = "Gtk_New"

  [[GtkImage.method]]
    id = "gtk_image_get_animation"
    ada = "Get"

  [[GtkImage.method]]
    id = "gtk_image_set_from_animation"
    ada = "Set"

  [[GtkImage.method]]
    id = "gtk_image_get_image"
    ada = "Get"

  [[GtkImage.method]]
    id = "gtk_image_get"
    bind = false
    # same as get_image

  [[GtkImage.method]]
    id = "gtk_image_set_from_image"
    ada = "Set"

  [[GtkImage.method]]
    id = "gtk_image_set"
    bind = false
    # same as set_from_image

  [[GtkImage.method]]
    id = "gtk_image_get_pixbuf"
    ada = "Get"

  [[GtkImage.method]]
    id = "gtk_image_set_from_pixbuf"
    ada = "Set"

  [[GtkImage.method]]
    id = "gtk_image_get_icon_set"
    ada = "Get"

  [[GtkImage.method]]
    id = "gtk_image_set_from_icon_set"
    ada = "Set"

  [[GtkImage.method]]
    id = "gtk_image_get_pixmap"
    ada = "Get"

  [[GtkImage.method]]
    id = "gtk_image_set_from_pixmap"
    ada = "Set"

  [[GtkImage.method]]
    id = "gtk_image_get_stock"
    ada = "Get"
    bind = false

  [[GtkImage.method]]
    id = "gtk_image_set_from_stock"
    ada = "Set"

  [[GtkImage.method]]
    id = "gtk_image_get_gicon"
    ada = "Get"

  [[GtkImage.method]]
    id = "gtk_image_set_from_gicon"
    ada = "Set"

  [[GtkImage.method]]
    id = "gtk_image_set_from_file"
    ada = "Set"

  [[GtkImage.method]]
    id = "gtk_image_get_icon_name"
    ada = "Get"
    bind = false

  [[GtkImage.enum]]
    ctype = "GtkImageType"

  [GtkImage.extra]
    body = '''

   procedure Get_Icon_Name
     (Image : access Gtk_Image_Record;
      Name  : out GNAT.Strings.String_Access;
      Size  : out Gtk_Icon_Size)
   is
      procedure Internal
        (Image : System.Address;
         Name  : out Gtkada.Types.Chars_Ptr;
         Size  : out Gtk_Icon_Size);
      pragma Import (C, Internal, "gtk_image_get_icon_name");
      Str : chars_ptr;
   begin
      Internal (Get_Object (Image), Str, Size);
      Name := new String'(Value (Str));
   end Get_Icon_Name;

   function Get
     (Image : access Gtk_Image_Record;
      Size  : access Gtk.Enums.Gtk_Icon_Size) return String
   is
      procedure Internal
        (Image    : System.Address;
         Stock_Id : out Gtkada.Types.Chars_Ptr;
         Size     : out Gint);
      pragma Import (C, Internal, "gtk_image_get_stock");

      Stock : Gtkada.Types.Chars_Ptr;
      Sze   : Gint;

   begin
      Internal (Get_Object (Image), Stock, Sze);
      Size.all := Gtk.Enums.Gtk_Icon_Size'Val (Sze);
      return Gtkada.Types.Value (Stock);
   end Get;
        '''

    [[GtkImage.extra.with_spec]]
      pkg = "GNAT.Strings"

    [[GtkImage.extra.spec]]
      text = '''

   function Get
     (Image : access Gtk_Image_Record;
      Size  : access Gtk.Enums.Gtk_Icon_Size) return String;
   --  Get the stock_id for the image displayed

   procedure Get_Icon_Name
     (Image : access Gtk_Image_Record;
      Name  : out GNAT.Strings.String_Access;
      Size  : out Gtk.Enums.Gtk_Icon_Size);
        '''