
# ============================================================
#   GtkIconView
# ============================================================
[GtkIconView]

  [[GtkIconView.parameter]]
    name = "self"
    ada = "Icon_View"

  [[GtkIconView.enum]]
    ctype = "GtkIconViewDropPosition"
    prefix = "GTK_ICON_VIEW_"

  [[GtkIconView.method]]
    id = "gtk_icon_view_get_cursor"
    return_as_param = "Cursor_Is_Set"

  [[GtkIconView.method]]
    id = "gtk_icon_view_get_dest_item_at_pos"
    return_as_param = "Has_Item"

  [[GtkIconView.method]]
    id = "gtk_icon_view_get_item_at_pos"
    return_as_param = "Has_Item"

  [[GtkIconView.method]]
    id = "gtk_icon_view_get_selected_items"
    return = "TreePathList"

  [[GtkIconView.method]]
    id = "gtk_icon_view_get_tooltip_context"
    return_as_param = "Success"

  [[GtkIconView.method]]
    id = "gtk_icon_view_get_visible_range"
    return = "void"

  [[GtkIconView.method]]
    id = "gtk_icon_view_enable_model_drag_source"
    bind = false
    # see below

  [[GtkIconView.method]]
    id = "gtk_icon_view_enable_model_drag_dest"
    bind = false
    # see below

  [GtkIconView.extra]
    body = '''

   procedure Enable_Model_Drag_Dest
     (Icon_View : access Gtk_Icon_View_Record;
      Targets   : Target_Entry_Array;
      Actions   : Drag_Action)
   is
      procedure Internal
        (Icon_View : System.Address;
         Targets   : System.Address;
         N_Targets : Gint;
         Actions   : Drag_Action);
      pragma Import (C, Internal, "gtk_icon_view_enable_model_drag_dest");
   begin
      Internal (Get_Object (Icon_View),
                Targets (Targets'First)'Address, Targets'Length,
                Actions);
   end Enable_Model_Drag_Dest;

   procedure Enable_Model_Drag_Source
     (Icon_View         : access Gtk_Icon_View_Record;
      Start_Button_Mask : Gdk_Modifier_Type;
      Targets           : Target_Entry_Array;
      Actions           : Drag_Action)
   is
      procedure Internal
        (Icon_View         : System.Address;
         Start_Button_Mask : Gdk_Modifier_Type;
         Targets           : System.Address;
         N_Targets         : Gint;
         Actions           : Drag_Action);
      pragma Import (C, Internal, "gtk_icon_view_enable_model_drag_source");
   begin
      Internal (Get_Object (Icon_View), Start_Button_Mask,
                Targets (Targets'First)'Address, Targets'Length,
                Actions);
   end Enable_Model_Drag_Source;
       '''

    [[GtkIconView.extra.with_spec]]
      pkg = "Gtk.Target_List"

    [[GtkIconView.extra.with_spec]]
      pkg = "Gdk.Dnd"

    [[GtkIconView.extra.with_spec]]
      pkg = "Gdk.Types"

    [[GtkIconView.extra.spec]]
      text = '''

   procedure Enable_Model_Drag_Dest
     (Icon_View : access Gtk_Icon_View_Record;
      Targets   : Gtk.Target_List.Target_Entry_Array;
      Actions   : Gdk.Dnd.Drag_Action);
   --  Turns Icon_view into a drop destination for automatic DND.
   --  Targets is the list of targets that the drag will support.

   procedure Enable_Model_Drag_Source
     (Icon_View         : access Gtk_Icon_View_Record;
      Start_Button_Mask : Gdk.Types.Gdk_Modifier_Type;
      Targets           : Gtk.Target_List.Target_Entry_Array;
      Actions           : Gdk.Dnd.Drag_Action);
   --  Turns Icon_view into a drag source for automatic DND.
   --  Start_Button_Mask is the allowed buttons to start drag.
       '''