
# ============================================================
#   GtkListBox
# ============================================================
[GtkListBox]

  [[GtkListBox.method]]
    id = "gtk_list_box_get_selected_rows"
    return = "ListBoxRowList"