# ============================================================
#   GtkLevelBar
# ============================================================

[doc]
group = "Display widgets"
gtkada_demo = "create_level_bar.adb"
