# ============================================================
#   GtkMessageDialog
# ============================================================

[[parameter]]
name = "self"
ada = "Dialog"

[[enum]]
ctype = "GtkMessageType"
prefix = "GTK_"

[[enum]]
ctype = "GtkButtonsType"
prefix = "GTK_"

[[method]]
id = "gtk_message_dialog_new"

[[method.parameter]]
name = "message_format"
ada = "message"
default = "\"\""

[[method.parameter]]
name = "varargs"
ada = ""
ctype = "gpointer"
default = "System.Null_Address"

[[method]]
id = "gtk_message_dialog_new_with_markup"

[[method.parameter]]
name = "message_format"
ada = "message"
default = "\"\""

[[method.parameter]]
name = "varargs"
ada = ""
ctype = "gpointer"
default = "System.Null_Address"

[[method]]
id = "gtk_message_dialog_format_secondary_markup"

[[method.parameter]]
name = "message_format"
ada = "message"
default = "\"\""

[[method.parameter]]
name = "varargs"
ada = ""
ctype = "gpointer"
default = "System.Null_Address"