# ============================================================
#   GtkMapListModel
# ============================================================

[[callback]]
id = "Gtk_Map_List_Model_Map_Func"
bind = false # manual implementation

[[method]]
id = "gtk_map_list_model_new"
bind = false # manual implementation

[[method]]
id = "gtk_map_list_model_set_map_func"
bind = false # manual implementation

[[extra.spec]]
text = '''
   ---------------
   -- Callbacks --
   ---------------

   type Gtk_Map_List_Model_Map_Func is access function (Item : Glib.Object.GObject) return Glib.Object.GObject;
   --  User function that is called to map an Item of the original model to an
   --  item expected by the map model.
   --  The returned items must conform to the item type of the model they are
   --  used with.
   --  Parameter Item has transfer-ownership='full'
   --  @param Item The item to map

   ------------------
   -- Constructors --
   ------------------

   procedure Gtk_New
      (Self     : out Gtk_Map_List_Model;
       Model    : Glib.List_Model.Glist_Model;
       Map_Func : Gtk_Map_List_Model_Map_Func);
   procedure Initialize
      (Self     : not null access Gtk_Map_List_Model_Record'Class;
       Model    : Glib.List_Model.Glist_Model;
       Map_Func : Gtk_Map_List_Model_Map_Func);
   --  Creates a new `GtkMapListModel` for the given arguments.
   --  Initialize does nothing if the object was already created with another
   --  call to Initialize* or G_New.
   --  @param Model The model to map
   --  @param Map_Func map function

   function Gtk_Map_List_Model_New
      (Model    : Glib.List_Model.Glist_Model;
       Map_Func : Gtk_Map_List_Model_Map_Func)
       return Gtk_Map_List_Model;
   --  Creates a new `GtkMapListModel` for the given arguments.
   --  @param Model The model to map
   --  @param Map_Func map function

   procedure Set_Map_Func
      (Self     : not null access Gtk_Map_List_Model_Record;
       Map_Func : Gtk_Map_List_Model_Map_Func);
   --  Sets the function used to map items.
   --  The function will be called whenever an item needs to be mapped and
   --  must return the item to use for the given input item.
   --  Note that `GtkMapListModel` may call this function multiple times on
   --  the same item, because it may delete items it doesn't need anymore.
   --  GTK makes no effort to ensure that Map_Func conforms to the item type
   --  of Self. It assumes that the caller knows what they are doing and the
   --  map function returns items of the appropriate type.
   --  @param Map_Func map function

   generic
      type User_Data_Type (<>) is private;
      with procedure Destroy (Data : in out User_Data_Type) is null;
   package Map_List_Model_User_Data is

      type Gtk_Map_List_Model_Map_User_Func is access function
        (Item      : Glib.Object.GObject;
         User_Data : User_Data_Type) return Glib.Object.GObject;
      --  User function that is called to map an Item of the original model to an
      --  item expected by the map model.
      --  The returned items must conform to the item type of the model they are
      --  used with.
      --  Parameter Item has transfer-ownership='full'
      --  Parameter Item has transfer-ownership='full'
      --  @param Item The item to map
      --  @param User_Data user data

      procedure Gtk_New_User
         (Self      : out Gtk_Map_List_Model;
          Model     : Glib.List_Model.Glist_Model;
          Map_Func  : Gtk_Map_List_Model_Map_User_Func;
          User_Data : User_Data_Type);

      procedure Initialize_User
         (Self      : not null access Gtk_Map_List_Model_Record'Class;
          Model     : Glib.List_Model.Glist_Model;
          Map_Func  : Gtk_Map_List_Model_Map_User_Func;
          User_Data : User_Data_Type);
      --  Creates a new filter using the given function to filter items.
      --  If Match_Func is `NULL`, the filter matches all items.
      --  If the filter func changes its filtering behavior,
      --  [methodGtk.Filter.changed] needs to be called.
      --  Initialize does nothing if the object was already created with another
      --  call to Initialize* or G_New.
      --  @param Match_Func function to filter items
      --  @param User_Data user data to pass to Match_Func

      function Gtk_Map_List_Model_New_User
         (Model     : Glib.List_Model.Glist_Model;
          Map_Func  : Gtk_Map_List_Model_Map_User_Func;
          User_Data : User_Data_Type)
          return Gtk_Map_List_Model;
      --  Creates a new filter using the given function to filter items.
      --  If Match_Func is `NULL`, the filter matches all items.
      --  If the filter func changes its filtering behavior,
      --  [methodGtk.Filter.changed] needs to be called.
      --  @param Match_Func function to filter items

      procedure Set_Map_Func
         (Self      : not null access Gtk.Map_List_Model.Gtk_Map_List_Model_Record'Class;
          Map_Func  : Gtk_Map_List_Model_Map_User_Func;
          User_Data : User_Data_Type);
      --  Sets the function used to map items.
      --  The function will be called whenever an item needs to be mapped and
      --  must return the item to use for the given input item.
      --  Note that `GtkMapListModel` may call this function multiple times on
      --  the same item, because it may delete items it doesn't need anymore.
      --  GTK makes no effort to ensure that Map_Func conforms to the item
      --  type of Self. It assumes that the caller knows what they are doing
      --  and the map function returns items of the appropriate type.
      --  @param Map_Func map function
      --  @param User_Data user data passed to Map_Func

   end Map_List_Model_User_Data;
'''

[[extra.with_body]]
pkg = "Ada.Unchecked_Conversion"
use = false

[extra]
body = '''
   function C_New
      (Model        : Glib.List_Model.Glist_Model;
       Map_Func     : System.Address;
       User_Data    : System.Address;
       User_Destroy : System.Address)
       return System.Address;
   pragma Import (C, C_New, "gtk_map_list_model_new");

   procedure C_Gtk_Map_List_Model_Set_Map_Func
      (Self         : System.Address;
       Map_Func     : System.Address;
       User_Data    : System.Address;
       User_Destroy : System.Address);
   pragma Import (C, C_Gtk_Map_List_Model_Set_Map_Func, "gtk_map_list_model_set_map_func");
   --  Sets the function used to map items.
   --  The function will be called whenever an item needs to be mapped and
   --  must return the item to use for the given input item.
   --  Note that `GtkMapListModel` may call this function multiple times on
   --  the same item, because it may delete items it doesn't need anymore.
   --  GTK makes no effort to ensure that Map_Func conforms to the item type
   --  of Self. It assumes that the caller knows what they are doing and the
   --  map function returns items of the appropriate type.
   --  @param Map_Func map function
   --  @param User_Data user data passed to Map_Func
   --  @param User_Destroy destroy notifier for User_Data

   function To_Gtk_Map_List_Model_Map_Func is new Ada.Unchecked_Conversion
     (System.Address, Gtk_Map_List_Model_Map_Func);

   function To_Address is new Ada.Unchecked_Conversion
     (Gtk_Map_List_Model_Map_Func, System.Address);

   function Internal_Gtk_Map_List_Model_Map_Func
      (Item      : System.Address;
       User_Data : System.Address) return System.Address;
   pragma Convention (C, Internal_Gtk_Map_List_Model_Map_Func);
   --  @param Item The item to map
   --  @param User_Data user data

   procedure Internal_Destroy (Data : System.Address) is null;
   pragma Convention (C, Internal_Destroy);

   ----------------------------
   -- Gtk_Map_List_Model_New --
   ----------------------------

   function Gtk_Map_List_Model_New
      (Model    : Glib.List_Model.Glist_Model;
       Map_Func : Gtk_Map_List_Model_Map_Func)
       return Gtk_Map_List_Model
   is
      Self : constant Gtk_Map_List_Model := new Gtk_Map_List_Model_Record;
   begin
      Gtk.Map_List_Model.Initialize (Self, Model, Map_Func);
      return Self;
   end Gtk_Map_List_Model_New;

   -------------
   -- Gtk_New --
   -------------

   procedure Gtk_New
      (Self     : out Gtk_Map_List_Model;
       Model    : Glib.List_Model.Glist_Model;
       Map_Func : Gtk_Map_List_Model_Map_Func) is
   begin
      Self := new Gtk_Map_List_Model_Record;
      Gtk.Map_List_Model.Initialize (Self, Model, Map_Func);
   end Gtk_New;

   ----------------
   -- Initialize --
   ----------------

   procedure Initialize
      (Self     : not null access Gtk_Map_List_Model_Record'Class;
       Model    : Glib.List_Model.Glist_Model;
       Map_Func : Gtk_Map_List_Model_Map_Func) is
   begin
      if not Self.Is_Created then
         if Map_Func = null then
            Set_Object
              (Self,
               C_New
                 (Model,
                  System.Null_Address,
                  System.Null_Address,
                  Internal_Destroy'Address));
         else
            Set_Object
              (Self,
               C_New
                 (Model,
                  Internal_Gtk_Map_List_Model_Map_Func'Address,
                  To_Address (Map_Func),
                  Internal_Destroy'Address));
         end if;
      end if;
   end Initialize;

   ------------------------------------------
   -- Internal_Gtk_Map_List_Model_Map_Func --
   ------------------------------------------

   function Internal_Gtk_Map_List_Model_Map_Func
      (Item      : System.Address;
       User_Data : System.Address) return System.Address
   is
      Func         : constant Gtk_Map_List_Model_Map_Func :=
        To_Gtk_Map_List_Model_Map_Func (User_Data);
      Stub_GObject : Glib.Object.GObject_Record;
   begin
      return Get_Object (Func (Get_User_Data (Item, Stub_GObject)));
   exception
      when others => return System.Null_Address;      
   end Internal_Gtk_Map_List_Model_Map_Func;

   ------------------
   -- Set_Map_Func --
   ------------------

   procedure Set_Map_Func
      (Self     : not null access Gtk_Map_List_Model_Record;
       Map_Func : Gtk_Map_List_Model_Map_Func)
   is
   begin
      if Map_Func = null then
         C_Gtk_Map_List_Model_Set_Map_Func
           (Get_Object (Self),
            System.Null_Address,
            System.Null_Address,
            Internal_Destroy'Address);
      else
         C_Gtk_Map_List_Model_Set_Map_Func
           (Get_Object (Self),
            Internal_Gtk_Map_List_Model_Map_Func'Address,
            To_Address (Map_Func),
            Internal_Destroy'Address);
      end if;
   end Set_Map_Func;

   ------------------------------
   -- Map_List_Model_User_Data --
   ------------------------------

   package body Map_List_Model_User_Data is

      package Users is new Glib.Object.User_Data_Closure
        (User_Data_Type, Destroy);

      function To_Gtk_Map_List_Model_Map_User_Func is new Ada.Unchecked_Conversion
        (System.Address, Gtk_Map_List_Model_Map_User_Func);

      function To_Address is new Ada.Unchecked_Conversion
        (Gtk_Map_List_Model_Map_User_Func, System.Address);

      function Internal_Cb
         (Item      : System.Address;
          User_Data : System.Address) return System.Address;
      pragma Convention (C, Internal_Cb);
      --  User function that is called to map an Item of the original model to
      --  an item expected by the map model.
      --  The returned items must conform to the item type of the model they
      --  are used with.
      --  Parameter Item has transfer-ownership='full'
      --  Parameter Item has transfer-ownership='full'
      --  @param Item The item to map
      --  @param User_Data user data

      -----------------
      -- Internal_Cb --
      -----------------

      function Internal_Cb
         (Item      : System.Address;
          User_Data : System.Address) return System.Address
      is
         D            : constant Users.Internal_Data_Access := Users.Convert (User_Data);
         Stub_GObject : Glib.Object.GObject_Record;
      begin
         return Get_Object
           (To_Gtk_Map_List_Model_Map_User_Func (D.Func)
             (Get_User_Data (Item, Stub_GObject), D.Data.all));
      exception
         when others => return System.Null_Address;      
      end Internal_Cb;

      ------------------
      -- Gtk_New_User --
      ------------------

      procedure Gtk_New_User
         (Self      : out Gtk_Map_List_Model;
          Model     : Glib.List_Model.Glist_Model;
          Map_Func  : Gtk_Map_List_Model_Map_User_Func;
          User_Data : User_Data_Type) is
      begin
        Self := new Gtk_Map_List_Model_Record;
        Map_List_Model_User_Data.Initialize_User (Self, Model, Map_Func, User_Data);
      end Gtk_New_User;

      ---------------------------------
      -- Gtk_Map_List_Model_New_User --
      ---------------------------------

      function Gtk_Map_List_Model_New_User
         (Model     : Glib.List_Model.Glist_Model;
          Map_Func  : Gtk_Map_List_Model_Map_User_Func;
          User_Data : User_Data_Type)
          return Gtk_Map_List_Model
      is
         Self : constant Gtk_Map_List_Model := new Gtk_Map_List_Model_Record;
      begin
         Map_List_Model_User_Data.Initialize_User (Self, Model, Map_Func, User_Data);
         return Self;
      end Gtk_Map_List_Model_New_User;

      ---------------------
      -- Initialize_User --
      ---------------------

      procedure Initialize_User
         (Self      : not null access Gtk_Map_List_Model_Record'Class;
          Model     : Glib.List_Model.Glist_Model;
          Map_Func  : Gtk_Map_List_Model_Map_User_Func;
          User_Data : User_Data_Type)
      is
         D : System.Address;
      begin
         if not Self.Is_Created then
            if Map_Func = null then
               Set_Object
                 (Self,
                  C_New
                    (Model,
                     System.Null_Address,
                     System.Null_Address,
                     Users.Free_Data'Address));
            else
               D := Users.Build (To_Address (Map_Func), User_Data);
               Set_Object
                 (Self,
                  C_New
                    (Model,
                     Internal_Cb'Address,
                     D,
                     Users.Free_Data'Address));
            end if;
         end if;
      end Initialize_User;

      ------------------
      -- Set_Map_Func --
      ------------------

      procedure Set_Map_Func
         (Self      : not null access Gtk.Map_List_Model.Gtk_Map_List_Model_Record'Class;
          Map_Func  : Gtk_Map_List_Model_Map_User_Func;
          User_Data : User_Data_Type)
      is
         D : System.Address;
      begin
         if Map_Func = null then
            C_Gtk_Map_List_Model_Set_Map_Func
              (Get_Object (Self),
               System.Null_Address,
               System.Null_Address,
               Users.Free_Data'Address);
         else
            D := Users.Build (To_Address (Map_Func), User_Data);
            C_Gtk_Map_List_Model_Set_Map_Func
              (Get_Object (Self),
               Internal_Cb'Address,
               D,
               Users.Free_Data'Address);
         end if;
      end Set_Map_Func;

   end Map_List_Model_User_Data;
'''