# ============================================================
#   GtkMenuButton
# ============================================================

[doc]
group = "Menus and Toolbars"
gtkada_demo = "create_menu.adb"
