
# ============================================================
#   GtkMenuBar
# ============================================================
[GtkMenuBar]

  [[GtkMenuBar.parameter]]
    name = "self"
    ada = "Menu_Bar"