
# ============================================================
#   GtkMenuShell
# ============================================================
[GtkMenuShell]

  [[GtkMenuShell.parameter]]
    name = "self"
    ada = "Menu_Shell"