# ============================================================
#   GtkNeverTrigger
# ============================================================

[[method]]
id = "gtk_never_trigger_get"
return = "GtkNeverTrigger"