# ============================================================
#   GtkNotebook
# ============================================================

[[enum]]
ctype = "GtkNotebookTab"

[doc]
screenshot = "gtk-notebook"
group = "Layout containers"
testgtk = "create_notebook.adb"

[[parameter]]
name = "self"
ada = "Notebook"

[[method]]
id = "gtk_notebook_set_scrollable"

[[method.parameter]]
name = "scrollable"
default = "True"

[[method]]
id = "gtk_notebook_set_tab_reorderable"

[[method.parameter]]
name = "reorderable"
default = "True"

[[method]]
id = "gtk_notebook_set_current_page"

[[method.parameter]]
name = "page_num"
default = "-1"

[[method]]
id = "gtk_notebook_set_show_border"

[[method.parameter]]
name = "show_border"
default = "True"

[[method]]
id = "gtk_notebook_append_page_menu"
return = "void"

[[method]]
id = "gtk_notebook_set_show_tabs"

[[method.parameter]]
name = "show_tabs"
default = "True"

[[method]]
id = "gtk_notebook_set_tab_detachable"

[[method.parameter]]
name = "detachable"
default = "True"

[extra]
body = '''

   procedure Append_Page
     (Notebook  : access Gtk_Notebook_Record;
      Child     : access Gtk.Widget.Gtk_Widget_Record'Class)
   is
      Ignored : Gint;
      pragma Unreferenced (Ignored);
   begin
      Ignored := Append_Page (Notebook, Child, null);
   end Append_Page;

   procedure Append_Page
     (Notebook  : access Gtk_Notebook_Record;
      Child     : access Gtk.Widget.Gtk_Widget_Record'Class;
      Tab_Label : access Gtk.Widget.Gtk_Widget_Record'Class)
   is
      Ignored : Gint;
      pragma Unreferenced (Ignored);
   begin
      Ignored := Append_Page (Notebook, Child, Tab_Label);
   end Append_Page;

   procedure Prepend_Page
     (Notebook  : access Gtk_Notebook_Record;
      Child     : access Gtk.Widget.Gtk_Widget_Record'Class;
      Tab_Label : access Gtk.Widget.Gtk_Widget_Record'Class)
   is
      Ignored : Gint;
      pragma Unreferenced (Ignored);
   begin
      Ignored := Append_Page (Notebook, Child, Tab_Label);
   end Prepend_Page;
        '''

[[extra.spec]]
text = '''

   procedure Append_Page
     (Notebook  : access Gtk_Notebook_Record;
      Child     : access Gtk.Widget.Gtk_Widget_Record'Class);
   procedure Append_Page
     (Notebook  : access Gtk_Notebook_Record;
      Child     : access Gtk.Widget.Gtk_Widget_Record'Class;
      Tab_Label : access Gtk.Widget.Gtk_Widget_Record'Class);
   procedure Prepend_Page
     (Notebook  : access Gtk_Notebook_Record;
      Child     : access Gtk.Widget.Gtk_Widget_Record'Class;
      Tab_Label : access Gtk.Widget.Gtk_Widget_Record'Class);
   --  Convenience functions, same as above but discarding the return value.
        '''