# ============================================================
#   GtkOverlay
# ============================================================

[doc]
group       = "Layout containers"
gtkada_demo = "create_overlay.adb"
