
# ============================================================
#   GtkPrintOperationPreview
# ============================================================
[GtkPrintOperationPreview]

  [[GtkPrintOperationPreview.parameter]]
    name = "self"
    ada = "Preview"