
# ============================================================
#   GtkPaned
# ============================================================
[GtkPaned]

  [GtkPaned.doc]
    screenshot = "gtk-paned"
    group = "Layout container"
    testgtk = "create_paned.adb"

  [[GtkPaned.parameter]]
    name = "self"
    ada = "Paned"

  [[GtkPaned.method]]
    id = "gtk_paned_pack1"

    [GtkPaned.method.doc]
      text = '''
Add a child to the top or left pane.
You can not change dynamically the attributes Resize and Shrink.
Instead, you have to remove the child from the container, and put it
back with the new value of the attributes. You should also first
call Glib.Object.Ref on the child so as to be sure it is not destroyed
when you remove it, and Glib.Object.Unref it at the end. See the
example in testgtk/ in the GtkAda distribution.'''

    [[GtkPaned.method.parameter]]
      name = "self"
      ada = "Paned"

    [[GtkPaned.method.parameter]]
      name = "resize"
      default = "False"

    [[GtkPaned.method.parameter]]
      name = "shrink"
      default = "True"

  [[GtkPaned.method]]
    id = "gtk_paned_pack2"

    [[GtkPaned.method.parameter]]
      name = "self"
      ada = "Paned"

    [[GtkPaned.method.parameter]]
      name = "resize"
      default = "False"

    [[GtkPaned.method.parameter]]
      name = "shrink"
      default = "False"

  [[GtkPaned.method]]
    id = "gtk_paned_add1"

    [GtkPaned.method.doc]
      text = '''
Add the first child of the container.
The child will be displayed either in the top or in the left pane,
depending on the orientation of the container.
This is equivalent to using the Pack1 procedure with its default parameters.'''

    [[GtkPaned.method.parameter]]
      name = "self"
      ada = "Paned"

  [[GtkPaned.method]]
    id = "gtk_paned_add2"

    [GtkPaned.method.doc]
      text = '''
Add the second child of the container.
It will be displayed in the bottom or right pane, depending on the
container's orientation.
This is equivalent to using Pack2 with its default parameters.'''

    [[GtkPaned.method.parameter]]
      name = "self"
      ada = "Paned"