
# ============================================================
#   GtkPixmap
# ============================================================
[GtkPixmap]

  [GtkPixmap.doc]
    group = "Obsolescent widgets"

  [[GtkPixmap.parameter]]
    name = "self"
    ada = "Pixmap"

  [[GtkPixmap.parameter]]
    name = "pixmap"
    ada = "Val"

  [[GtkPixmap.method]]
    id = "gtk_pixmap_set_build_insensitive"

    [GtkPixmap.method.doc]
      text = "Whether the pixmap should be grayed out, as is done for insensitive widgets that do not accept user interaction"

  [GtkPixmap.extra]
    body = '''

   Dummy_Pixmap : constant Gtkada.Types.chars_ptr_array :=
     (New_String ("1 1 1 1"),
      New_String ("c None"),
      New_String (" "));
   --  This is a dummy pixmap we use when a pixmap can't be found.

   function Create_Pixmap
     (Filename : String;
      Window   : access Gtk.Window.Gtk_Window_Record'Class) return Gtk_Pixmap
   is
      Gdkpixmap : Gdk.Pixmap.Gdk_Pixmap;
      Mask      : Gdk.Bitmap.Gdk_Bitmap;
      Pixmap    : Gtk_Pixmap;

      use Gtk.Widget;
      use Gtk.Window;

   begin
      if not Realized_Is_Set (Window) then
         Gtk.Window.Realize (Window);
      end if;

      if Filename = "" then
         Gdk.Pixmap.Create_From_Xpm_D
           (Gdkpixmap, Get_Window (Window), Mask,
            Gdk.Color.Null_Color, Dummy_Pixmap);
      else
         Gdk.Pixmap.Create_From_Xpm
           (Gdkpixmap, Get_Window (Window), Mask,
            Gdk.Color.Null_Color, Filename);
      end if;

      Gtk_New (Pixmap, Gdkpixmap, Mask);
      return Pixmap;
   end Create_Pixmap;

   function Create_Pixmap
     (Data   : Gtkada.Types.Chars_Ptr_Array;
      Window : access Gtk.Window.Gtk_Window_Record'Class) return Gtk_Pixmap
   is
      Gdkpixmap : Gdk.Pixmap.Gdk_Pixmap;
      Mask      : Gdk.Bitmap.Gdk_Bitmap;
      Pixmap    : Gtk_Pixmap;

      use Gtk.Widget;
      use Gtk.Window;

   begin
      if not Realized_Is_Set (Window) then
         Gtk.Window.Realize (Window);
      end if;

      Gdk.Pixmap.Create_From_Xpm_D
        (Gdkpixmap, Get_Window (Window), Mask, Gdk.Color.Null_Color, Data);
      Gtk_New (Pixmap, Gdkpixmap, Mask);

      return Pixmap;
   end Create_Pixmap;
         '''

    [[GtkPixmap.extra.with_spec]]
      pkg = "Gtk.Widget"

    [[GtkPixmap.extra.with_spec]]
      pkg = "Gtk.Window"

    [[GtkPixmap.extra.with_spec]]
      pkg = "Gtkada.Types"

    [[GtkPixmap.extra.with_body]]
      pkg = "Gdk.Color"

    [[GtkPixmap.extra.spec]]
      text = '''

   function Create_Pixmap
     (Filename : String;
      Window   : access Gtk.Window.Gtk_Window_Record'Class) return Gtk_Pixmap;
      --  Create a pixmap given a window and a filename

   function Create_Pixmap
     (Data     : Gtkada.Types.Chars_Ptr_Array;
      Window   : access Gtk.Window.Gtk_Window_Record'Class) return Gtk_Pixmap;
   --  Create a pixmap given a window and a buffer.
            '''