# ============================================================
#   GtkPasswordEntry
# ============================================================

[doc]
group       = "Numeric/Text Data Entry"
gtkada_demo = "create_password_entry.adb"
