
# ============================================================
#   GtkPrintContext
# ============================================================
[GtkPrintContext]

  [[GtkPrintContext.parameter]]
    name = "self"
    ada = "Context"