# ============================================================
#   GtkPrintOperation
# ============================================================

[[enum]]
ctype = "GtkPrintOperationAction"

[[enum]]
ctype = "GtkPrintOperationResult"
