
# ============================================================
#   GtkRecentFilter
# ============================================================
[GtkRecentFilter]

  [[GtkRecentFilter.parameter]]
    name = "self"
    ada = "Filter"

  [[GtkRecentFilter.enum]]
    ctype = "GtkRecentFilterFlags"

  [[GtkRecentFilter.record]]
    ctype = "GtkRecentFilterInfo"

  [[GtkRecentFilter.slist]]
    ada = "Gtk_Recent_Filter_List"
    ctype = "GtkRecentFilter"