# ============================================================
#   GtkRecentInfo
# ============================================================
# into="GtkRecentManager">

[[method]]
id = "gtk_recent_info_ref"
return = "void"
# ??? Disabled for now, we are creating an unconstrained local var

[[method]]
id = "gtk_recent_info_get_application_info"
bind = false
return = "void"
# These functions return the length separately, not needed in Ada

[[method]]
id = "gtk_recent_info_get_applications"
bind = false

[[method]]
id = "gtk_recent_info_get_groups"
bind = false

[extra]

[[extra.type]]
text = '''

   subtype time_t is Long_Integer;
   --  Type to interface with C's time_t type.  To convert this to/from
   --  an Ada type, look at Ada.Calendar.Conversion_Operations and be
   --  sure to pay special attention to the ranges each type is capable
   --  of representing.
       '''