
# ============================================================
#   GtkRecentChooserWidget
# ============================================================
[GtkRecentChooserWidget]

  [[GtkRecentChooserWidget.parameter]]
    name = "self"
    ada = "Widget"