# ============================================================
#   GtkRecentFilter
# ============================================================

[[parameter]]
name = "self"
ada = "Filter"

[[enum]]
ctype = "GtkRecentFilterFlags"

[[record]]
ctype = "GtkRecentFilterInfo"

[[slist]]
ada = "Gtk_Recent_Filter_List"
ctype = "GtkRecentFilter"