
# ============================================================
#   GtkRevealer
# ============================================================
[GtkRevealer]

  [[GtkRevealer.enum]]
    ctype = "GtkRevealerTransitionType"