# ============================================================
#   GtkRecentAction
# ============================================================

[[parameter]]
name = "self"
ada = "Widget"

[[method]]
id = "gtk_recent_action_new_for_manager"

[[method.parameter]]
name = "manager"
default = "Gtk.Recent_Manager.Get_Default"