
# ============================================================
#   GtkStack
# ============================================================
[GtkStack]

  [[GtkStack.enum]]
    ctype = "GtkStackTransitionType"