
# ============================================================
#   GtkScrollbar
# ============================================================
[GtkScrollbar]

  [[GtkScrollbar.parameter]]
    name = "self"
    ada = "Scrollbar"