
# ============================================================
#   GtkScrollable
# ============================================================
[GtkScrollable]

  [GtkScrollable.doc]
    group = "Interfaces"