# ============================================================
#   GtkScale
# ============================================================

[doc]
screenshot = "gtk-scale.png"
group = "Numeric/Text Data Entry"

[[parameter]]
name = "self"
ada = "Scale"