
# ============================================================
#   GtkSeparatorToolItem
# ============================================================
[GtkSeparatorToolItem]

  [GtkSeparatorToolItem.doc]
    group = "Menus and Toolbars"

  [[GtkSeparatorToolItem.parameter]]
    name = "self"
    ada = "Item"