# ============================================================
#   GtkStackSwitcher
# ============================================================

[doc]
group       = "Layout containers"
gtkada_demo = "create_stack.adb"
