
# ============================================================
#   GtkStyleContext
# ============================================================
[GtkStyleContext]

  [[GtkStyleContext.enum]]
    ctype = "GtkStyleContextPrintFlags"

  [[GtkStyleContext.method]]
    id = "gtk_style_context_has_region"
    return_as_param = "Is_Defined"

  [[GtkStyleContext.method]]
    id = "gtk_style_context_list_classes"
    return = "StringList"

  [[GtkStyleContext.method]]
    id = "gtk_style_context_list_regions"
    return = "StringList"

  [[GtkStyleContext.method]]
    id = "gtk_style_context_get_valist"
    bind = false
    # needs valist

  [[GtkStyleContext.method]]
    id = "gtk_style_context_get_style_valist"
    bind = false
    # needs valist

  [[GtkStyleContext.method]]
    id = "gtk_style_context_lookup_color"
    return_as_param = "Found"

  [[GtkStyleContext.method]]
    id = "gtk_style_context_state_is_running"
    return_as_param = "Is_Running"

  [[GtkStyleContext.method]]
    id = "gtk_style_context_lookup_icon_set"
    bind = false
    # in GtkIconSet

  [[GtkStyleContext.function]]
    id = "gtk_render_handle"

  [[GtkStyleContext.function]]
    id = "gtk_render_check"

  [[GtkStyleContext.function]]
    id = "gtk_render_option"

  [[GtkStyleContext.function]]
    id = "gtk_render_arrow"

  [[GtkStyleContext.function]]
    id = "gtk_render_background"

  [[GtkStyleContext.function]]
    id = "gtk_render_frame"

  [[GtkStyleContext.function]]
    id = "gtk_render_expander"

  [[GtkStyleContext.function]]
    id = "gtk_render_focus"

  [[GtkStyleContext.function]]
    id = "gtk_render_layout"

  [[GtkStyleContext.function]]
    id = "gtk_render_line"

  [[GtkStyleContext.function]]
    id = "gtk_render_slider"

  [[GtkStyleContext.function]]
    id = "gtk_render_frame_gap"

  [[GtkStyleContext.function]]
    id = "gtk_render_extension"

  [[GtkStyleContext.function]]
    id = "gtk_render_activity"
    # <function id="gtk_render_icon_pixbuf" />

  [[GtkStyleContext.function]]
    id = "gtk_render_icon"

  [[GtkStyleContext.function]]
    id = "gtk_render_icon_surface"

  [GtkStyleContext.extra]
    body = '''

   function Get_Style_Context
      (Widget : not null access Gtk_Widget_Record'Class)
       return Gtk_Style_Context
   is
      function Internal (Widget : System.Address) return System.Address;
      pragma Import (C, Internal, "gtk_widget_get_style_context");
      Stub_Gtk_Style_Context : Gtk_Style_Context_Record;
   begin
      return Gtk_Style_Context
         (Get_User_Data (Internal (Get_Object (Widget)), Stub_Gtk_Style_Context));
   end Get_Style_Context;
       '''

    [[GtkStyleContext.extra.spec]]
      text = '''

   function Get_Style_Context
      (Widget : not null access Gtk_Widget_Record'Class)
       return Gtk_Style_Context;
   --  Returns the style context associated to Widget.
   --  must not be freed.
       '''