# ============================================================
#   GtkSpinner
# ============================================================

[doc]
group = "Ornaments"

[[parameter]]
name = "self"
ada = "Spinner"