
# ============================================================
#   GtkScaleButton
# ============================================================
[GtkScaleButton]

  [[GtkScaleButton.parameter]]
    name = "self"
    ada = "Button"