# ============================================================
#   GtkSizeGroup
# ============================================================

[doc]
testgtk = "create_size_groups.adb"

[[parameter]]
name = "self"
ada = "Size_Group"

[[method]]
id = "gtk_size_group_new"

[[method.parameter]]
name = "mode"
default = "Both"

[[method]]
id = "gtk_size_group_get_widgets"
return = "WidgetSList"

[[enum]]
ctype = "GtkSizeGroupMode"
ada = "Size_Group_Mode"
prefix = "GTK_SIZE_GROUP_"