# ============================================================
#   GtkSpinButton
# ============================================================

[[parameter]]
name = "self"
ada = "Spin_Button"

[[enum]]
ctype = "GtkSpinType"

[[enum]]
ctype = "GtkSpinButtonUpdatePolicy"

[[method]]
id = "gtk_spin_button_new_with_range"
ada = "Gtk_New"

[[method]]
id = "gtk_spin_button_new"

[[method.parameter]]
name = "digits"
default = "0"