# ============================================================
#   GtkSeparator
# ============================================================

[doc]
screenshot = "gtk-separator"
group = "Ornaments"

