
# ============================================================
#   GtkScale
# ============================================================
[GtkScale]

  [GtkScale.doc]
    screenshot = "gtk-scale.png"
    group = "Numeric/Text Data Entry"

  [[GtkScale.parameter]]
    name = "self"
    ada = "Scale"