# ============================================================
#   GtkShortcutAction
# ============================================================

[[enum]]
ctype = "GtkShortcutActionFlags"
asbitfield = true

[[method]]
id = "gtk_shortcut_action_parse_string"
ada = "Gtk_New"
