# ============================================================
#   GtkScale
# ============================================================

[doc]
group = "Numeric/Text Data Entry"
gtkada_demo = "create_scale.adb"
