
# ============================================================
#   GtkSpinner
# ============================================================
[GtkSpinner]

  [GtkSpinner.doc]
    group = "Ornaments"

  [[GtkSpinner.parameter]]
    name = "self"
    ada = "Spinner"