# ============================================================
#   GtkSearchEntry
# ============================================================

[doc]
group       = "Numeric/Text Data Entry"
gtkada_demo = "create_entry.adb"
