# ============================================================
#   GtkTreeListModel
# ============================================================

[[method]]
id = "gtk_tree_list_model_new"
bind = false # manual implementatuion belowe

[[extra.spec]]
text = '''
   ---------------
   -- Callbacks --
   ---------------
   
   type Gtk_Tree_List_Model_Create_Model_Func is access function
     (Item : Glib.Object.GObject) return Glib.List_Model.Glist_Model;
   --  Prototype of the function called to create new child models when
   --  gtk_tree_list_row_set_expanded() is called.

   --  This function can return %NULL to indicate that @item is guaranteed to be
   --  a leaf node and will never have children. If it does not have children but
   --  may get children later, it should return an empty model that is filled once
   --  children arrive.
   --  @param Item The item that is being expanded
   --  Return has transfer-ownership='full'
   --  @retrun The model tracking the children of
   --   item or NULL if item can never have children.

   ------------------
   -- Constructors --
   ------------------

   procedure Gtk_New
      (Self        : out Gtk_Tree_List_Model;
       Root        : Glib.List_Model.Glist_Model;
       Passthrough : Boolean;
       Autoexpand  : Boolean;
       Create_Func : Gtk_Tree_List_Model_Create_Model_Func);
   procedure Initialize
      (Self        : not null access Gtk_Tree_List_Model_Record'Class;
       Root        : Glib.List_Model.Glist_Model;
       Passthrough : Boolean;
       Autoexpand  : Boolean;
       Create_Func : Gtk_Tree_List_Model_Create_Model_Func);
   --  Creates a new empty `GtkTreeListModel` displaying Root with all rows
   --  collapsed.
   --  Initialize does nothing if the object was already created with another
   --  call to Initialize* or G_New.
   --  @param Root The `GListModel` to use as root
   --  @param Passthrough True to pass through items from the models
   --  @param Autoexpand True to set the autoexpand property and expand the
   --  Root model
   --  @param Create_Func function to call to create the `GListModel` for the
   --  children of an item

   function Gtk_Tree_List_Model_New
      (Root        : Glib.List_Model.Glist_Model;
       Passthrough : Boolean;
       Autoexpand  : Boolean;
       Create_Func : Gtk_Tree_List_Model_Create_Model_Func)
       return Gtk_Tree_List_Model;
   --  Creates a new empty `GtkTreeListModel` displaying Root with all rows
   --  collapsed.
   --  @param Root The `GListModel` to use as root
   --  @param Passthrough True to pass through items from the models
   --  @param Autoexpand True to set the autoexpand property and expand the
   --  Root model
   --  @param Create_Func function to call to create the `GListModel` for the
   --  children of an item

   generic
      type User_Data_Type (<>) is private;
      with procedure Destroy (Data : in out User_Data_Type) is null;
   package Gtk_Tree_List_Model_User_Data is

      type Gtk_Tree_List_Model_Create_Model_User_Func is access function
        (Item : Glib.Object.GObject; User_Data : User_Data_Type)
         return Glib.List_Model.Glist_Model;

      procedure Gtk_New_User
         (Self         : out Gtk_Tree_List_Model;
          Root         : Glib.List_Model.Glist_Model;
          Passthrough  : Boolean;
          Autoexpand   : Boolean;
          Create_Func  : Gtk_Tree_List_Model_Create_Model_User_Func;
          User_Data    : User_Data_Type);
      procedure Initialize_User
         (Self         : not null access Gtk_Tree_List_Model_Record'Class;
          Root         : Glib.List_Model.Glist_Model;
          Passthrough  : Boolean;
          Autoexpand   : Boolean;
          Create_Func  : Gtk_Tree_List_Model_Create_Model_User_Func;
          User_Data    : User_Data_Type);
      --  Creates a new empty `GtkTreeListModel` displaying Root with all rows
      --  collapsed.
      --  Initialize does nothing if the object was already created with another
      --  call to Initialize* or G_New.
      --  @param Root The `GListModel` to use as root
      --  @param Passthrough True to pass through items from the models
      --  @param Autoexpand True to set the autoexpand property and expand the
      --  Root model
      --  @param Create_Func function to call to create the `GListModel` for the
      --  children of an item
      --  @param User_Data Data to pass to Create_Func

      function Gtk_Tree_List_Model_New_User
         (Root         : Glib.List_Model.Glist_Model;
          Passthrough  : Boolean;
          Autoexpand   : Boolean;
          Create_Func  : Gtk_Tree_List_Model_Create_Model_User_Func;
          User_Data    : User_Data_Type)
          return Gtk_Tree_List_Model;
      --  Creates a new empty `GtkTreeListModel` displaying Root with all rows
      --  collapsed.
      --  @param Root The `GListModel` to use as root
      --  @param Passthrough True to pass through items from the models
      --  @param Autoexpand True to set the autoexpand property and expand the
      --  Root model
      --  @param Create_Func function to call to create the `GListModel` for the
      --  children of an item
      --  @param User_Data Data to pass to Create_Func
   end Gtk_Tree_List_Model_User_Data;
'''

[[extra.with_body]]
pkg = "Ada.Unchecked_Conversion"
use = false

[extra]
body = '''
   function C_New
      (Root         : Glib.List_Model.Glist_Model;
       Passthrough  : Glib.Gboolean;
       Autoexpand   : Glib.Gboolean;
       Create_Func  : System.Address;
       User_Data    : System.Address;
       User_Destroy : System.Address)
       return System.Address;
   pragma Import (C, C_New, "gtk_tree_list_model_new");

   function To_Gtk_Tree_List_Model_Create_Model_Func is new Ada.Unchecked_Conversion
     (System.Address, Gtk_Tree_List_Model_Create_Model_Func);
   
   function To_Address is new Ada.Unchecked_Conversion
     (Gtk_Tree_List_Model_Create_Model_Func, System.Address);
   
   function Internal_Gtk_Tree_List_Model_Create_Model_Func
      (Item      : System.Address;
       User_Data : System.Address) return Glib.List_Model.Glist_Model;
   pragma Convention (C, Internal_Gtk_Tree_List_Model_Create_Model_Func);
   --  @param Item The item to map
   --  @param User_Data user data
   
   procedure Internal_Destroy (Data : System.Address) is null;
   pragma Convention (C, Internal_Destroy);

   -------------
   -- Gtk_New --
   -------------

   procedure Gtk_New
      (Self        : out Gtk_Tree_List_Model;
       Root        : Glib.List_Model.Glist_Model;
       Passthrough : Boolean;
       Autoexpand  : Boolean;
       Create_Func : Gtk_Tree_List_Model_Create_Model_Func) is
   begin
      Self := new Gtk_Tree_List_Model_Record;
      Gtk.Tree_List_Model.Initialize (Self, Root, Passthrough, Autoexpand, Create_Func);
   end Gtk_New;

   -----------------------------
   -- Gtk_Tree_List_Model_New --
   -----------------------------

   function Gtk_Tree_List_Model_New
      (Root        : Glib.List_Model.Glist_Model;
       Passthrough : Boolean;
       Autoexpand  : Boolean;
       Create_Func : Gtk_Tree_List_Model_Create_Model_Func)
       return Gtk_Tree_List_Model
   is
      Self : constant Gtk_Tree_List_Model := new Gtk_Tree_List_Model_Record;
   begin
      Gtk.Tree_List_Model.Initialize (Self, Root, Passthrough, Autoexpand, Create_Func);
      return Self;
   end Gtk_Tree_List_Model_New;

   ----------------
   -- Initialize --
   ----------------

   procedure Initialize
      (Self        : not null access Gtk_Tree_List_Model_Record'Class;
       Root        : Glib.List_Model.Glist_Model;
       Passthrough : Boolean;
       Autoexpand  : Boolean;
       Create_Func : Gtk_Tree_List_Model_Create_Model_Func) is
   begin
      if not Self.Is_Created then
         if Create_Func = null then
            Set_Object
              (Self,
               C_New
                 (Root,
                  Boolean'Pos (Passthrough),
                  Boolean'Pos (Autoexpand),
                  System.Null_Address,
                  System.Null_Address,
                  Internal_Destroy'Address));
         else
            Set_Object
              (Self,
               C_New
                 (Root,
                  Boolean'Pos (Passthrough),
                  Boolean'Pos (Autoexpand),
                  Internal_Gtk_Tree_List_Model_Create_Model_Func'Address,
                  To_Address (Create_Func),
                  Internal_Destroy'Address));
         end if;
      end if;
   end Initialize;

   ----------------------------------------------------
   -- Internal_Gtk_Tree_List_Model_Create_Model_Func --
   ----------------------------------------------------

   function Internal_Gtk_Tree_List_Model_Create_Model_Func
      (Item      : System.Address;
       User_Data : System.Address) return Glib.List_Model.Glist_Model
   is
      Func         : constant Gtk_Tree_List_Model_Create_Model_Func :=
        To_Gtk_Tree_List_Model_Create_Model_Func (User_Data);
      Stub_GObject : Glib.Object.GObject_Record;
   begin
      return Func (Get_User_Data (Item, Stub_GObject));
   exception
      when others => return Glib.List_Model.Null_Glist_Model;
   end Internal_Gtk_Tree_List_Model_Create_Model_Func;

   -----------------------------------
   -- Gtk_Tree_List_Model_User_Data --
   -----------------------------------

   package body Gtk_Tree_List_Model_User_Data is

      package Users is new Glib.Object.User_Data_Closure
        (User_Data_Type, Destroy);
      
      function To_Gtk_Tree_List_Model_Create_Model_User_Func is new Ada.Unchecked_Conversion
        (System.Address, Gtk_Tree_List_Model_Create_Model_User_Func);
   
      function To_Address is new Ada.Unchecked_Conversion
        (Gtk_Tree_List_Model_Create_Model_User_Func, System.Address);
      
      function Internal_Cb
         (Item      : System.Address;
          User_Data : System.Address) return Glib.List_Model.Glist_Model;
      pragma Convention (C, Internal_Cb);

      -----------------
      -- Internal_Cb --
      -----------------
   
      function Internal_Cb
         (Item      : System.Address;
          User_Data : System.Address) return Glib.List_Model.Glist_Model
      is
         D            : constant Users.Internal_Data_Access := Users.Convert (User_Data);
         Stub_GObject : Glib.Object.GObject_Record;
      begin
         return To_Gtk_Tree_List_Model_Create_Model_User_Func (D.Func)
            (Get_User_Data (Item, Stub_GObject), D.Data.all);
      exception
         when others => return Glib.List_Model.Null_Glist_Model;
      end Internal_Cb;

      ------------------
      -- Gtk_New_User --
      ------------------

      procedure Gtk_New_User
         (Self         : out Gtk_Tree_List_Model;
          Root         : Glib.List_Model.Glist_Model;
          Passthrough  : Boolean;
          Autoexpand   : Boolean;
          Create_Func  : Gtk_Tree_List_Model_Create_Model_User_Func;
          User_Data    : User_Data_Type)
      is
      begin
         Self := new Gtk_Tree_List_Model_Record;
         Gtk_Tree_List_Model_User_Data.Initialize_User
           (Self, Root, Passthrough, Autoexpand, Create_Func, User_Data);
      end Gtk_New_User;

      ----------------------------------
      -- Gtk_Tree_List_Model_New_User --
      ----------------------------------

      function Gtk_Tree_List_Model_New_User
         (Root         : Glib.List_Model.Glist_Model;
          Passthrough  : Boolean;
          Autoexpand   : Boolean;
          Create_Func  : Gtk_Tree_List_Model_Create_Model_User_Func;
          User_Data    : User_Data_Type)
          return Gtk_Tree_List_Model
      is
         Self : constant Gtk_Tree_List_Model := new Gtk_Tree_List_Model_Record;
      begin
         Gtk_Tree_List_Model_User_Data.Initialize_User
           (Self, Root, Passthrough, Autoexpand, Create_Func, User_Data);
         return Self;
      end Gtk_Tree_List_Model_New_User;

      ---------------------
      -- Initialize_User --
      ---------------------

      procedure Initialize_User
         (Self         : not null access Gtk_Tree_List_Model_Record'Class;
          Root         : Glib.List_Model.Glist_Model;
          Passthrough  : Boolean;
          Autoexpand   : Boolean;
          Create_Func  : Gtk_Tree_List_Model_Create_Model_User_Func;
          User_Data    : User_Data_Type)
      is
        D : System.Address;
      begin
         if not Self.Is_Created then
            if Create_Func = null then
               Set_Object
                 (Self,
                  C_New
                    (Root,
                     Boolean'Pos (Passthrough),
                     Boolean'Pos (Autoexpand),
                     System.Null_Address,
                     System.Null_Address,
                     Users.Free_Data'Address));
            else
               D := Users.Build (To_Address (Create_Func), User_Data);
               Set_Object
                 (Self,
                  C_New
                    (Root,
                     Boolean'Pos (Passthrough),
                     Boolean'Pos (Autoexpand),
                     Internal_Cb'Address,
                     D,
                     Users.Free_Data'Address));
            end if;
         end if;
      end Initialize_User;

   end Gtk_Tree_List_Model_User_Data;
'''