
# ============================================================
#   GtkTreeRowReference
# ============================================================
[GtkTreeRowReference]

  [[GtkTreeRowReference.parameter]]
    name = "self"
    ada = "Reference"