
# ============================================================
#   GtkToggleAction
# ============================================================
[GtkToggleAction]

  [[GtkToggleAction.parameter]]
    name = "self"
    ada = "Action"