# ============================================================
#   GtkToggleButton
# ============================================================

[doc]
screenshot = "gtk-toggle_button"
group = "Buttons and Toggles"
testgtk = "create_toggle_buttons.adb"
text = '''
You should consider using a Gtk_Check_Button instead, since it looks nicer and provides more visual clues that the button can be toggled.
     '''

[[parameter]]
name = "self"
ada = "Toggle_Button"

[[method]]
id = "gtk_toggle_button_new"
bind = false

[[method]]
id = "gtk_toggle_button_new_with_label"
ada = "Gtk_New"

[method.doc]
text = "Initialize a button. If Label is \"\", then no label is created inside the button and you will have to provide your own child through a call to Gtk.Container.Add. This is the recommended way to put a pixmap inside a toggle button."

[[method.parameter]]
name = "label"
default = "\"\""
allow_none = "1"

[[method]]
id = "gtk_toggle_button_set_active"

[method.doc]
text = "Change the state of the button. When Is_Active is True, the button is drawn as a pressed button"

[[method]]
id = "gtk_toggle_button_set_inconsistent"

[[method.parameter]]
name = "Setting"
default = "True"