
# ============================================================
#   GtkTextTag
# ============================================================
[GtkTextTag]

  [[GtkTextTag.parameter]]
    name = "self"
    ada = "Tag"

  [[GtkTextTag.method]]
    id = "::event"
    bind = false

  [[GtkTextTag.method]]
    id = "gtk_text_tag_new"

    [GtkTextTag.method.doc]
      extend = true
      text = '''
Newly created tags must be added to the tags table for the buffer you
intend to use them in, as in:
 "Gtk.Text_Tag_Table.Add (Get_Tag_Table (Buffer), Tag)".
See also Gtk.Text_Buffer.Create_Tag which is a more convenient way of
creating a tag.'''

  [[GtkTextTag.method]]
    id = "gtk_text_tag_event"
    bind = false
    # circular dep with text_iter

  [[GtkTextTag.slist]]
    ada = "Text_Tag_List"
    ctype = "GtkTextTag"