# ============================================================
#   GtkTextAttributes
# ============================================================

[[parameter]]
name = "self"
ada = "Text_Attr"

[[record]]
ctype = "GtkTextAppearance"