# ============================================================
#   GtkTryExpression
# ============================================================

[[method]]
id = "gtk_try_expression_new"
bind = false

[[extra.spec]]
text = '''
   procedure Gtk_New
      (Self        : out Gtk_Try_Expression;
       Expressions : Gtk.Expression.Gtk_Expression_Array);
   procedure Initialize
      (Self        : not null access Gtk_Try_Expression_Record'Class;
       Expressions : Gtk.Expression.Gtk_Expression_Array);
   --  Creates a `GtkExpression` with an array of expressions.
   --  When evaluated, the `GtkTryExpression` tries to evaluate each of its
   --  expressions until it succeeds. If all expressions fail to evaluate, the
   --  `GtkTryExpression`'s evaluation fails as well.
   --  The value type of the expressions in the array must match.
   --  Since: gtk+ 4.22
   --  Initialize does nothing if the object was already created with another
   --  call to Initialize* or G_New.
   --  @param Expressions The array of expressions'''

[extra]
body = '''
   -------------
   -- Gtk_New --
   -------------

   procedure Gtk_New
      (Self        : out Gtk_Try_Expression;
       Expressions : Gtk.Expression.Gtk_Expression_Array)
   is
   begin
      Self := new Gtk_Try_Expression_Record;
      Gtk.Try_Expression.Initialize (Self, Expressions);
   end Gtk_New;

   ----------------
   -- Initialize --
   ----------------

   procedure Initialize
      (Self        : not null access Gtk_Try_Expression_Record'Class;
       Expressions : Gtk.Expression.Gtk_Expression_Array)
   is
      function Internal
         (N_Expressions   : Guint;
          Acc_Expressions : System.Address)
          return System.Address;
      pragma Import (C, Internal, "gtk_try_expression_new");
      Acc_Expressions : Gtk.Expression.C_GtkExpressionArray :=
        Gtk.Expression.To_C (Expressions);
   begin
      if not Self.Is_Created then
         --  transfer-ownership="full"
         for Expression of Expressions loop
            if Expression /= null then
               Adjust (Expression.all);
            end if;
         end loop;

         Set_Object (Self, Internal (Guint (Acc_Expressions'Length), Acc_Expressions'Address));
      end if;
   end Initialize;'''