
# ============================================================
#   GtkTearoffMenuItem
# ============================================================
[GtkTearoffMenuItem]

  [[GtkTearoffMenuItem.parameter]]
    name = "self"
    ada = "Menu_Item"