
# ============================================================
#   GtkTreeModel
# ============================================================
[GtkTreeModel]

  [[GtkTreeModel.parameter]]
    name = "self"
    ada = "Tree_Model"

  [[GtkTreeModel.enum]]
    ctype = "GtkTreeModelFlags"
    ada = "Tree_Model_Flags"

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_get"
    bind = false
    # varargs

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_get_valist"
    bind = false
    # varargs

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_get_iter"
    return = "Gtk_Tree_Iter"
    body = '''
      function Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter : System.Address; Path : System.Address) return Gint;
      pragma Import (C, Internal, "gtk_tree_model_get_iter");
      Iter : aliased Gtk_Tree_Iter;
   begin
      if Internal (+Tree_Model, Iter'Address, Get_Object (Path)) /= 0 then
         return Iter;
      else
         return Null_Iter;
      end if;'''

    [[GtkTreeModel.method.parameter]]
      name = "iter"
      ada = ""

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_get_iter_from_string"
    return = "Gtk_Tree_Iter"
    body = '''
      function Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter : System.Address; Str : String) return Gint;
      pragma Import (C, Internal, "gtk_tree_model_get_iter_from_string");
      Iter : aliased Gtk_Tree_Iter;
   begin
      if Internal
        (+Tree_Model, Iter'Address, Path_String & ASCII.NUL) /= 0
      then
         return Iter;
      else
         return Null_Iter;
      end if;'''

    [[GtkTreeModel.method.parameter]]
      name = "iter"
      ada = ""

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_get_iter_first"
    return = "Gtk_Tree_Iter"
    body = '''
      function Internal
         (Tree_Model : Gtk_Tree_Model; Iter : System.Address) return Gint;
      pragma Import (C, Internal, "gtk_tree_model_get_iter_first");
      Iter : aliased Gtk_Tree_Iter;
   begin
      if Internal (+Tree_Model, Iter'Address) /= 0 then
         return Iter;
      else
         return Null_Iter;
      end if;'''

    [[GtkTreeModel.method.parameter]]
      name = "iter"
      ada = ""

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_iter_next"
    ada = "Next"
    return = "void"
    body = '''
      function Internal
         (Tree_Model : Gtk_Tree_Model; Iter : System.Address) return Gint;
      pragma Import (C, Internal, "gtk_tree_model_iter_next");
      Local_Iter : aliased Gtk_Tree_Iter := Iter;
   begin
      if Internal (+Tree_Model, Local_Iter'Address) = 0 then
         Iter := Null_Iter;
      else
         Iter := Local_Iter;
      end if;'''

    [[GtkTreeModel.method.parameter]]
      name = "iter"
      direction = "inout"

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_iter_previous"
    ada = "Previous"
    return = "void"
    body = '''
      function Internal
         (Tree_Model : Gtk_Tree_Model; Iter : System.Address) return Gint;
      pragma Import (C, Internal, "gtk_tree_model_iter_previous");
      Local_Iter : aliased Gtk_Tree_Iter := Iter;
   begin
      if Internal (+Tree_Model, Local_Iter'Address) = 0 then
         Iter := Null_Iter;
      else
         Iter := Local_Iter;
      end if;'''

    [[GtkTreeModel.method.parameter]]
      name = "iter"
      direction = "inout"

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_iter_children"
    ada = "Children"
    return = "Gtk_Tree_Iter"
    body = '''
      function Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter       : System.Address;
         Parent     : System.Address) return Gint;
      pragma Import (C, Internal, "gtk_tree_model_iter_children");
      It : aliased Gtk_Tree_Iter;
   begin
      if Internal (+Tree_Model, It'Address, Iter_Or_Null (Parent'Address)) /= 0 then
         return It;
      else
         return Null_Iter;
      end if;'''

    [[GtkTreeModel.method.parameter]]
      name = "iter"
      ada = ""

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_iter_has_child"
    ada = "Has_Child"

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_iter_n_children"
    ada = "N_Children"
    body = '''
      function Internal
          (Tree_Model : Gtk_Tree_Model; Iter : System.Address) return Gint;
      pragma Import (C, Internal, "gtk_tree_model_iter_n_children");
   begin
      return Internal (+Tree_Model, Iter_Or_Null (Iter'Address));'''

    [[GtkTreeModel.method.parameter]]
      name = "iter"
      default = "Gtk.Tree_Model.Null_Iter"

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_iter_nth_child"
    ada = "Nth_Child"
    return = "Gtk_Tree_Iter"
    body = '''
      function Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter, Parent : System.Address; N : Gint) return Gint;
      pragma Import (C, Internal, "gtk_tree_model_iter_nth_child");
      Iter : aliased Gtk_Tree_Iter;
   begin
      if Internal (+Tree_Model, Iter'Address, Iter_Or_Null (Parent'Address), N) /= 0 then
         return Iter;
      else
         return Null_Iter;
      end if;'''

    [[GtkTreeModel.method.parameter]]
      name = "iter"
      ada = ""

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_iter_parent"
    ada = "Parent"
    return = "Gtk_Tree_Iter"
    body = '''
      function Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter       : System.Address;
         Child      : Gtk_Tree_Iter) return Gint;
      pragma Import (C, Internal, "gtk_tree_model_iter_parent");
      Iter : aliased Gtk_Tree_Iter;
   begin
      if Internal (+Tree_Model, Iter'Address, Child) /= 0 then
         return Iter;
      else
         return Null_Iter;
      end if;'''

    [[GtkTreeModel.method.parameter]]
      name = "iter"
      ada = ""

  [[GtkTreeModel.method]]
    id = "gtk_tree_model_rows_reordered"

    [[GtkTreeModel.method.parameter]]
      name = "new_order"
      type = "Gint_Array"

  [GtkTreeModel.extra]
    body = '''

   function Get_Int
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Gint is
   begin
     return Get_Int (To_Interface (Tree_Model), Iter, Column);
   end Get_Int;

   function Get_Int
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Gint
   is
      procedure Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter       : Gtk_Tree_Iter;
         Column     : Gint;
         Value      : out Gint);
      pragma Import (C, Internal, "ada_gtk_tree_model_get");
      A : Gint;
   begin
      if Iter = Null_Iter then
         raise Program_Error with "Get_Int with null_iter";
      end if;
      Internal (Tree_Model, Iter, Column, A);
      return A;
   end Get_Int;

   function Get_Ulong
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Gulong is
   begin
     return Get_Ulong (To_Interface (Tree_Model), Iter, Column);
   end Get_Ulong;

   function Get_Ulong
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Gulong
   is
      procedure Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter       : Gtk_Tree_Iter;
         Column     : Gint;
         Value      : out Gulong);
      pragma Import (C, Internal, "ada_gtk_tree_model_get");
      A : Gulong;
   begin
      if Iter = Null_Iter then
         raise Program_Error with "Get_Ulong with null_iter";
      end if;
      Internal (Tree_Model, Iter, Column, A);
      return A;
   end Get_Ulong;

   function Get_Boolean
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Boolean is
   begin
      return Get_Boolean (To_Interface (Tree_Model), Iter, Column);
   end Get_Boolean;

   function Get_Boolean
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Boolean is
   begin
      return Get_Int (Tree_Model, Iter, Column) /= 0;
   end Get_Boolean;

   function Get_Object
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Glib.Object.GObject
   is
   begin
      return Get_Object (To_Interface (Tree_Model), Iter, Column);
   end Get_Object;

   function Get_Object
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Glib.Object.GObject
   is
      Stub : Glib.Object.GObject_Record;
   begin
      return Get_User_Data
         (Get_Address (Tree_Model, Iter, Column), Stub);
   end Get_Object;

   function Get_C_Proxy
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Glib.C_Proxy is
   begin
      return Get_C_Proxy (To_Interface (Tree_Model), Iter, Column);
   end Get_C_Proxy;

   function Get_C_Proxy
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Glib.C_Proxy
   is
      procedure Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter       : Gtk_Tree_Iter;
         Column     : Gint;
         Value      : out Glib.C_Proxy);
      pragma Import (C, Internal, "ada_gtk_tree_model_get");
      A : Glib.C_Proxy;
   begin
      if Iter = Null_Iter then
         raise Program_Error with "Get_C_Proxy with null_iter";
      end if;
      Internal (Tree_Model, Iter, Column, A);
      return A;
   end Get_C_Proxy;

   function Get_String
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return UTF8_String
   is
   begin
      return Get_String (To_Interface (Tree_Model), Iter, Column);
   end Get_String;

   function Get_String
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return UTF8_String
   is
      procedure Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter       : Gtk_Tree_Iter;
         Column     : Gint;
         Value      : out Gtkada.Types.Chars_Ptr);
      pragma Import (C, Internal, "ada_gtk_tree_model_get");
      A : Gtkada.Types.Chars_Ptr;
   begin
      if Iter = Null_Iter then
         raise Program_Error with "Get_String with null_iter";
      end if;
      Internal (Tree_Model, Iter, Column, A);
      if A = Gtkada.Types.Null_Ptr then
         return "";
      else
         return Gtkada.Bindings.Value_And_Free (A);
      end if;
   end Get_String;

   function Get_Address
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return System.Address
   is
   begin
      return Get_Address (To_Interface (Tree_Model), Iter, Column);
   end Get_Address;

   function Get_Address
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return System.Address
   is
      procedure Internal
        (Tree_Model : Gtk_Tree_Model;
         Iter       : Gtk_Tree_Iter;
         Column     : Gint;
         Value      : out System.Address);
      pragma Import (C, Internal, "ada_gtk_tree_model_get");
      A : System.Address;
   begin
      if Iter = Null_Iter then
         raise Program_Error with "Get_Address with null_iter";
      end if;
      Internal (Tree_Model, Iter, Column, A);
      return A;
   end Get_Address;
       '''

    [[GtkTreeModel.extra.spec]]
      text = '''

   type Gtk_Root_Tree_Model_Record is new Glib.Object.GObject_Record
      with null record;
   type Gtk_Root_Tree_Model is
      access all Gtk_Root_Tree_Model_Record'Class;
   --  A common base type for all objects that implement GtkTreeModel. This
   --  is used to conveniently provide a number of primitive operations.

   function Get_Int
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Gint;
   function Get_Ulong
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Gulong;
   function Get_Boolean
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Boolean;
   function Get_Object
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Glib.Object.GObject;
   function Get_C_Proxy
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Glib.C_Proxy;
   function Get_String
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return UTF8_String;
   function Get_Address
     (Tree_Model : access Gtk_Root_Tree_Model_Record;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return System.Address;
   --  Get the value of one cell of the model

   function Get_Int
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Gint;
   function Get_Ulong
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Gulong;
   function Get_Boolean
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Boolean;
   function Get_Object
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Glib.Object.GObject;
   function Get_C_Proxy
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return Glib.C_Proxy;
   function Get_String
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return UTF8_String;
   function Get_Address
     (Tree_Model : Gtk_Tree_Model;
      Iter       : Gtk_Tree_Iter;
      Column     : Gint) return System.Address;

   package Implements_Gtk_Tree_Model is new Glib.Types.Implements
     (Gtk_Tree_Model, Gtk_Root_Tree_Model_Record, Gtk_Root_Tree_Model);
   function To_Interface
     (Widget : access Gtk_Root_Tree_Model_Record'Class)
     return Gtk_Tree_Model renames Implements_Gtk_Tree_Model.To_Interface;
   function "-"
     (Interf : Gtk_Tree_Model) return Gtk_Root_Tree_Model
     renames Implements_Gtk_Tree_Model.To_Object;
   --  Convert from the gtk+ interface to an actual object. The return type
   --  depends on the exact model, and will likely be an instance of
   --  Gtk_Tree_Store'Class or Gtk_List_Store'Class depending on how you
   --  created it.
       '''