# ============================================================
#   GtkTreeListRow
# ============================================================

[[method]]
id = "gtk_tree_list_row_get_item"
return = "GObject.Object"