
# ============================================================
#   GtkToggleToolButton
# ============================================================
[GtkToggleToolButton]

  [[GtkToggleToolButton.parameter]]
    name = "self"
    ada = "Button"