
# ============================================================
#   GtkTextBuffer
# ============================================================
[GtkTextBuffer]

  [[GtkTextBuffer.parameter]]
    name = "self"
    ada = "Buffer"
    # the following involve a complex callback type and are not needed

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_register_serialize_format"
    bind = false

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_register_deserialize_format"
    bind = false

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_serialize"
    bind = false

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_deserialize"
    bind = false

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_get_serialize_formats"
    bind = false

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_get_deserialize_formats"
    bind = false

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_new"

    [[GtkTextBuffer.method.parameter]]
      name = "table"
      default = "null"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_create_mark"

    [[GtkTextBuffer.method.parameter]]
      name = "left_gravity"
      default = "True"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_get_text"

    [[GtkTextBuffer.method.parameter]]
      name = "include_hidden_chars"
      default = "False"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_get_slice"

    [[GtkTextBuffer.method.parameter]]
      name = "include_hidden_chars"
      default = "False"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_paste_clipboard"

    [[GtkTextBuffer.method.parameter]]
      name = "override_location"
      ada = ""
      ctype = "gpointer"
      default = "System.Null_Address"

    [[GtkTextBuffer.method.parameter]]
      name = "default_editable"
      default = "True"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_get_selection_bounds"
    return_as_param = "Result"

    [[GtkTextBuffer.method.parameter]]
      name = "start"
      direction = "out"

    [[GtkTextBuffer.method.parameter]]
      name = "end"
      direction = "out"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_delete"

    [[GtkTextBuffer.method.parameter]]
      name = "start"
      direction = "inout"

    [[GtkTextBuffer.method.parameter]]
      name = "end"
      direction = "inout"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_delete_interactive"
    return_as_param = "Result"

    [[GtkTextBuffer.method.parameter]]
      name = "start"
      direction = "inout"

    [[GtkTextBuffer.method.parameter]]
      name = "end"
      direction = "inout"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_insert"

    [[GtkTextBuffer.method.parameter]]
      name = "iter"
      direction = "inout"

    [[GtkTextBuffer.method.parameter]]
      name = "len"
      ada = ""
      default = "-1"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_insert_interactive"

    [[GtkTextBuffer.method.parameter]]
      name = "iter"
      direction = "inout"

    [[GtkTextBuffer.method.parameter]]
      name = "len"
      ada = ""
      default = "-1"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_insert_interactive_at_cursor"

    [[GtkTextBuffer.method.parameter]]
      name = "len"
      ada = ""
      default = "-1"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_set_text"

    [[GtkTextBuffer.method.parameter]]
      name = "len"
      ada = ""
      default = "-1"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_insert_at_cursor"

    [[GtkTextBuffer.method.parameter]]
      name = "len"
      ada = ""
      default = "-1"

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_create_tag"
    bind = false
    # vararg, bound manually below

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_insert_with_tags"
    bind = false
    # vararg, bound manually below
    # body bound manually to add safety check

  [[GtkTextBuffer.method]]
    id = "gtk_text_buffer_get_iter_at_line_offset"
    body = '''
      procedure Internal
         (Buffer      : System.Address;
          Iter        : out Gtk.Text_Iter.Gtk_Text_Iter;
          Line_Number : Gint;
          Char_Offset : Gint);
      pragma Import (C, Internal, "gtk_text_buffer_get_iter_at_line_offset");
      Result   : Boolean;
   begin
      --  Prevent critical crashes from gtk+ if Char_Offset is invalid
      Internal (Get_Object (Buffer), Iter, Line_Number, 0);

      if not Ends_Line (Iter) then
         Forward_To_Line_End (Iter, Result);

         if Char_Offset <= Get_Line_Offset (Iter) then
            Internal (Get_Object (Buffer), Iter, Line_Number, Char_Offset);
         end if;
      end if;'''

  [GtkTextBuffer.extra]
    body = '''

   ------------
   -- Insert --
   ------------

   procedure Insert
     (Buffer : access Gtk_Text_Buffer_Record;
      Iter   : in out Gtk.Text_Iter.Gtk_Text_Iter;
      Text   : Gtkada.Types.Chars_Ptr)
   is
      procedure Internal
        (Buffer : System.Address;
         Iter   : Gtk.Text_Iter.Gtk_Text_Iter;
         Text   : Gtkada.Types.Chars_Ptr;
         Len    : Gint := -1);
      pragma Import (C, Internal, "gtk_text_buffer_insert");

   begin
      Internal (Get_Object (Buffer), Iter, Text);
   end Insert;

   procedure Insert_At_Cursor
     (Buffer : access Gtk_Text_Buffer_Record;
      Text   : Gtkada.Types.Chars_Ptr;
      Len    : Gint := -1)
   is
      procedure Internal
        (Buffer : System.Address;
         Text   : Gtkada.Types.Chars_Ptr;
         Len    : Gint);
      pragma Import (C, Internal, "gtk_text_buffer_insert_at_cursor");

   begin
      Internal (Get_Object (Buffer), Text, Len);
   end Insert_At_Cursor;

   procedure Insert_With_Tags
     (Buffer : access Gtk_Text_Buffer_Record;
      Iter   : in out Gtk.Text_Iter.Gtk_Text_Iter;
      Text   : UTF8_String;
      Tag    : Gtk_Text_Tag)
   is
      procedure Internal
        (Buffer : System.Address;
         Iter   : in out Gtk.Text_Iter.Gtk_Text_Iter;
         Text   : UTF8_String;
         Len    : Gint;
         Tag    : System.Address);
      pragma Import (C, Internal, "ada_gtk_text_buffer_insert_with_tags");

   begin
      Internal
        (Get_Object (Buffer), Iter, Text, Text'Length, Get_Object (Tag));
   end Insert_With_Tags;

   procedure Insert_With_Tags
     (Buffer : access Gtk_Text_Buffer_Record;
      Iter   : in out Gtk.Text_Iter.Gtk_Text_Iter;
      Text   : Gtkada.Types.Chars_Ptr;
      Tag    : Gtk.Text_Tag.Gtk_Text_Tag)
   is
      procedure Internal
        (Buffer : System.Address;
         Iter   : in out Gtk.Text_Iter.Gtk_Text_Iter;
         Text   : Gtkada.Types.Chars_Ptr;
         Len    : Gint := -1;
         Tag    : System.Address);
      pragma Import (C, Internal, "ada_gtk_text_buffer_insert_with_tags");

   begin
      Internal (Get_Object (Buffer), Iter, Text, Tag => Get_Object (Tag));
   end Insert_With_Tags;

   --------------
   -- Get_Text --
   --------------

   function Get_Text
     (Buffer               : access Gtk_Text_Buffer_Record;
      Start                : Gtk.Text_Iter.Gtk_Text_Iter;
      The_End              : Gtk.Text_Iter.Gtk_Text_Iter;
      Include_Hidden_Chars : Boolean := False) return Gtkada.Types.Chars_Ptr
   is
      function Internal
        (Buffer               : System.Address;
         Start                : Gtk.Text_Iter.Gtk_Text_Iter;
         The_End              : Gtk.Text_Iter.Gtk_Text_Iter;
         Include_Hidden_Chars : Gboolean)
         return Gtkada.Types.Chars_Ptr;
      pragma Import (C, Internal, "gtk_text_buffer_get_text");

   begin
      return Internal
        (Get_Object (Buffer),
         Start,
         The_End,
         Boolean'Pos (Include_Hidden_Chars));
   end Get_Text;

   function Selection_Exists
     (Buffer : access Gtk_Text_Buffer_Record) return Boolean
   is
      Ignored_A, Ignored_B : Gtk_Text_Iter;
      Has_Selection : Boolean;
   begin
      Get_Selection_Bounds (Buffer, Ignored_A, Ignored_B, Has_Selection);
      return Has_Selection;
   end Selection_Exists;

   ----------------
   -- Get_Buffer --
   ----------------

   function Get_Buffer
      (Iter : Gtk_Text_Iter) return Gtk.Text_Buffer.Gtk_Text_Buffer
   is
      function Internal (Iter : Gtk_Text_Iter) return System.Address;
      pragma Import (C, Internal, "gtk_text_iter_get_buffer");
      Stub_Gtk_Text_Buffer : Gtk.Text_Buffer.Gtk_Text_Buffer_Record;
   begin
      return Gtk.Text_Buffer.Gtk_Text_Buffer (Get_User_Data (Internal (Iter), Stub_Gtk_Text_Buffer));
   end Get_Buffer;

   ----------------
   -- Get_Buffer --
   ----------------

   function Get_Buffer
      (Mark : Gtk_Text_Mark)
       return Gtk.Text_Buffer.Gtk_Text_Buffer
   is
      function Internal (Mark : System.Address) return System.Address;
      pragma Import (C, Internal, "gtk_text_mark_get_buffer");
      Stub_Gtk_Text_Buffer : Gtk.Text_Buffer.Gtk_Text_Buffer_Record;
   begin
      return Gtk.Text_Buffer.Gtk_Text_Buffer (Get_User_Data (Internal (Get_Object (Mark)), Stub_Gtk_Text_Buffer));
   end Get_Buffer;

   ----------------
   -- Create_Tag --
   ----------------

   function Create_Tag
     (Buffer              : access Gtk_Text_Buffer_Record;
      Tag_Name            : String := "")
      return Gtk_Text_Tag
   is
      function Internal
        (Buffer              : System.Address;
         Tag_Name            : Gtkada.Types.Chars_Ptr)
         return System.Address;
      pragma Import (C, Internal, "ada_gtk_text_buffer_create_tag");
      Stub : Gtk_Text_Tag_Record;
      Str  : Gtkada.Types.Chars_Ptr := String_Or_Null (Tag_Name);
      Tag  : Gtk_Text_Tag;
   begin
      Tag := Gtk_Text_Tag
        (Get_User_Data (Internal (Get_Object (Buffer), Str), Stub));
      Free (Str);
      return Tag;
   end Create_Tag;
       '''

    [[GtkTextBuffer.extra.with_spec]]
      pkg = "Gtkada.Types"

    [[GtkTextBuffer.extra.spec]]
      text = '''

   procedure Insert
     (Buffer : access Gtk_Text_Buffer_Record;
      Iter   : in out Gtk.Text_Iter.Gtk_Text_Iter;
      Text   : Gtkada.Types.Chars_Ptr);
   --  More efficient version of Insert, which doesn't require a string copy.

   procedure Insert_At_Cursor
     (Buffer : access Gtk_Text_Buffer_Record;
      Text   : Gtkada.Types.Chars_Ptr;
      Len    : Gint := -1);
   --  Call Buffer_Insert, using the current cursor position
   --  as the insertion point.
   --  Text: UTF-8 format C string to insert.

   function Get_Text
     (Buffer               : access Gtk_Text_Buffer_Record;
      Start                : Gtk.Text_Iter.Gtk_Text_Iter;
      The_End              : Gtk.Text_Iter.Gtk_Text_Iter;
      Include_Hidden_Chars : Boolean := False) return Gtkada.Types.Chars_Ptr;
   --  Same as Get_Text above, but return a pointer to a C string, for
   --  efficiency.
   --  The caller is responsible for freeing (using Gtkada.Types.g_free) the
   --  returned pointer.

   function Selection_Exists
     (Buffer : access Gtk_Text_Buffer_Record) return Boolean;
   --  Return True if some text in the buffer is currently selected.

   procedure Insert_With_Tags
     (Buffer : access Gtk_Text_Buffer_Record;
      Iter   : in out Gtk.Text_Iter.Gtk_Text_Iter;
      Text   : UTF8_String;
      Tag    : Gtk_Text_Tag);
   procedure Insert_With_Tags
     (Buffer : access Gtk_Text_Buffer_Record;
      Iter   : in out Gtk.Text_Iter.Gtk_Text_Iter;
      Text   : Gtkada.Types.Chars_Ptr;
      Tag    : Gtk.Text_Tag.Gtk_Text_Tag);
   --  Same as Insert, but specifies the tag to apply to the range.

   function Get_Buffer
      (Iter : Gtk_Text_Iter) return Gtk.Text_Buffer.Gtk_Text_Buffer;
   --  Returns the Gtk.Text_Buffer.Gtk_Text_Buffer this iterator is associated
   --  with.

   function Get_Buffer
      (Mark : Gtk_Text_Mark)
       return Gtk.Text_Buffer.Gtk_Text_Buffer;
   --  Gets the buffer this mark is located inside, or null if the mark is
   --  deleted.

   function Create_Tag
     (Buffer              : access Gtk_Text_Buffer_Record;
      Tag_Name            : String := "")
      return Gtk.Text_Tag.Gtk_Text_Tag;
   --  Creates a tag and adds it to the tag table for Buffer. Equivalent to
   --  calling gtk.text_tag.gtk_new and then adding the tag to the buffer's tag
   --  table. The returned tag is owned by the buffer's tag table, so the ref
   --  count will be equal to one.
   --
   --  If Tag_Name is NULL, the tag is anonymous, otherwise a tag called
   --  Tag_Name must not already exist in the tag table for this buffer.
       '''