# ============================================================
#   GtkVRuler
# ============================================================
into = "GtkRuler"

[[type]]
name = "Gtk_Vruler"
subtype = true

[[method]]
id = "gtk_vruler_new"
ada = "Gtk_New_Vruler"

[[parameter]]
name = "self"
ada = "Ruler"

[[method]]
id = "gtk_vruler_get_type"
ada = "Vruler_Get_Type"