# ============================================================
#   GtkViewport
# ============================================================

[doc]
group = "Scrolling"

[[parameter]]
name = "self"
ada = "Viewport"

[[method]]
id = "gtk_viewport_new"

[[method.parameter]]
name = "hadjustment"
default = "null"

[[method.parameter]]
name = "vadjustment"
default = "null"
# These are now inherited from the Scrollable interface

[[method]]
id = "gtk_viewport_get_hadjustment"
bind = false

[[method]]
id = "gtk_viewport_get_vadjustment"
bind = false

[[method]]
id = "gtk_viewport_set_hadjustment"
bind = false

[[method]]
id = "gtk_viewport_set_vadjustment"
bind = false