# ============================================================
#   GtkVPaned
# ============================================================
into = "GtkPaned"

[[type]]
name = "Gtk_Vpaned"
subtype = true

[[parameter]]
name = "self"
ada = "Paned"

[[method]]
id = "gtk_vpaned_new"
ada = "Gtk_New_Vpaned"

[method.doc]
text = "The children will be displayed one on top of the other"

[[method]]
id = "gtk_vpaned_get_type"
ada = "Get_Type_Vpaned"