# ============================================================
#   GtkVScale
# ============================================================
into = "GtkScale"

[[parameter]]
name = "self"
ada = "Scale"

[[type]]
name = "Gtk_Vscale"
subtype = true

[[method]]
id = "gtk_vscale_new"
ada = "Gtk_New_Vscale"

[[method.parameter]]
name = "adjustment"
default = "null"

[[method]]
id = "gtk_vscale_new_with_range"
ada = "Gtk_New_Vscale"

[[method]]
id = "gtk_vscale_get_type"
ada = "Vscale_Get_Type"