# ============================================================
#   GtkVBox
# ============================================================
into = "GtkBox"

[[type]]
name = "Gtk_Vbox"
subtype = true

[[method]]
id = "gtk_vbox_new"
ada = "Gtk_New_Vbox"

[[method.parameter]]
name = "homogeneous"
default = "False"

[[method.parameter]]
name = "spacing"
default = "0"

[[parameter]]
name = "self"
ada = "Box"

[[method]]
id = "gtk_vbox_get_type"
ada = "Get_Vbox_Type"