
# ============================================================
#   GtkVolumeButton
# ============================================================
[GtkVolumeButton]

  [[GtkVolumeButton.parameter]]
    name = "self"
    ada = "Widget"