# ============================================================
#   GtkVSeparator
# ============================================================
into = "GtkSeparator"

[[type]]
name = "Gtk_Vseparator"
subtype = true

[[method]]
id = "gtk_vseparator_new"
ada = "Gtk_New_Vseparator"

[[parameter]]
name = "self"
ada = "Separator"

[[method]]
id = "gtk_vseparator_get_type"
ada = "Vseparator_Get_Type"