
# ============================================================
#   GtkWindowGroup
# ============================================================
[GtkWindowGroup]
  into = "GtkWindow"

  [[GtkWindowGroup.parameter]]
    name = "self"
    ada = "Window_Group"

  [[GtkWindowGroup.method]]
    id = "gtk_window_group_get_type"
    ada = "Group_Get_Type"

  [[GtkWindowGroup.method]]
    id = "gtk_window_group_list_windows"
    return = "WidgetList"