
# ============================================================
#   PangoEnums
# ============================================================
[PangoEnums]

  [[PangoEnums.enum]]
    ctype = "PangoAlignment"
    ada = "Alignment"

  [[PangoEnums.enum]]
    ctype = "PangoAttrType"
    ada = "Attr_Type"

  [[PangoEnums.enum]]
    ctype = "PangoCoverageLevel"
    ada = "Coverage_Level"

  [[PangoEnums.enum]]
    ctype = "PangoDirection"
    ada = "Direction"

  [[PangoEnums.enum]]
    ctype = "PangoFontMask"
    ada = "Font_Mask"

  [[PangoEnums.enum]]
    ctype = "PangoGravity"
    ada = "Gravity"

  [[PangoEnums.enum]]
    ctype = "PangoGravityHint"
    ada = "GravityHint"

  [[PangoEnums.enum]]
    ctype = "PangoStretch"
    ada = "Stretch"

  [[PangoEnums.enum]]
    ctype = "PangoStyle"
    ada = "Style"

  [[PangoEnums.enum]]
    ctype = "PangoUnderline"
    ada = "Underline"

  [[PangoEnums.enum]]
    ctype = "PangoVariant"
    ada = "Variant"

  [[PangoEnums.enum]]
    ctype = "PangoWeight"
    ada = "Weight"

  [[PangoEnums.enum]]
    ctype = "PangoWrapMode"
    ada = "Wrap_Mode"

  [PangoEnums.extra]
    body = '''

   function To_Pixels (Pango_Units : Gint) return Gint is
   begin
      if Pango_Units > 0 then
         return (Pango_Units + Pango_Scale / 2) / Pango_Scale;
      else
         return (Pango_Units - Pango_Scale / 2) / Pango_Scale;
      end if;
   end To_Pixels;
       '''

    [[PangoEnums.extra.with_spec]]
      pkg = "Glib"

    [[PangoEnums.extra.spec]]
      text = '''

   Pango_Scale : constant := 1024;
   --  All internal units in Pango are expressed in terms of this unit. A
   --  typical pango size must be divided by Pango_Scale to get the equivalent
   --  in pixels.

   function To_Pixels (Pango_Units : Gint) return Gint;
   --  Convert a size in pango units to pixels. This is a rounding of
   --  Pango_Units divided by Pango_Scale

   --  Enum types are bound with the following algorithm:
   --    + the "Pango" prefix of the type name is stripped
   --    + Each word of the type name is separated by '_'
   --    + the full enum name is kept, but capitalized.

   --  All enums types should be sorted by alphabetical order...
       '''