# ============================================================
#   PangoMatrix
# ============================================================

[[record]]
ctype = "PangoMatrix"

[[method]]
id = "pango_matrix_rotate"

[[method.parameter]]
name = "self"
direction = "inout"

[[method]]
id = "pango_matrix_scale"

[[method.parameter]]
name = "self"
direction = "inout"

[[method]]
id = "pango_matrix_translate"

[[method.parameter]]
name = "self"
direction = "inout"