# ============================================================
#   PangoFont
# ============================================================

[[parameter]]
name = "self"
ada = "Font"

[[method]]
id = "pango_font_get_type"
ada = "Font_Get_Type"

[[method]]
id = "pango_font_find_shaper"
bind = false
# internal implementation of gtk

[[method]]
id = "pango_font_describe"
classwide = true

[[method]]
id = "pango_font_describe_with_absolute_size"
classwide = true

[[method]]
id = "pango_font_descriptions_free"
bind = false
# in Ada, need iteration

[[method]]
id = "pango_font_get_coverage"
bind = false
# circular dependency

[[method]]
id = "pango_font_get_font_map"
bind = false
# circular dependency

[[method]]
id = "pango_font_get_face"
bind = false
# circular dependency

[[method]]
id = "pango_font_get_features"
bind = false
# Harfbuzz required

[[method]]
id = "pango_font_get_hb_font"
bind = false
# Harfbuzz required

[[method]]
id = "pango_font_get_metrics"

[[method.parameter]]
name = "language"
default = "Pango.Language.Null_Pango_Language"