
# ============================================================
#   PangoFontMap
# ============================================================
[PangoFontMap]

  [PangoFontMap.doc]
    text = '''
An object that represents the set of fonts available for a particular
     rendering system'''

  [[PangoFontMap.method]]
    id = "pango_font_map_get_family"
    bind = false
    # more recent than 1.44

  [PangoFontMap.extra]

    [[PangoFontMap.extra.with_spec]]
      pkg = "Pango.Font_Family"

  [[PangoFontMap.method]]
    id = "pango_font_map_list_families"
    return = "Pango_Font_Family_Array"
    body = '''
      type font_family_array_bounded is array (Natural) of System.Address;

      procedure Internal
         (Self     : System.Address;
          Families : System.Address;
          Size     : access Gint);
      pragma Import (C, Internal, "pango_font_map_list_families");

      procedure g_free (s : access font_family_array_bounded);
      pragma Import (C, g_free, "g_free");

      Families : aliased access font_family_array_bounded;
      Size : aliased Gint;
      Tmplt : Pango_Font_Family_Record;
   begin
      Internal (Self.Get_Object, Families'Address, Size'Access);

      declare
         Result : Pango_Font_Family_Array (1 .. Integer (Size));
      begin
         for R in 0 .. Integer (Size) - 1 loop
             Result (R + 1) := Pango_Font_Family
                (Get_User_Data (Families (R), Tmplt));
         end loop;
         g_free (Families);

         return Result;
      end;'''

    [[PangoFontMap.method.parameter]]
      name = "families"
      ada = ""

    [[PangoFontMap.method.parameter]]
      name = "n_families"
      ada = ""