
# ============================================================
#   PangoAttrList
# ============================================================
[PangoAttrList]
  into = "PangoAttribute"

  [[PangoAttrList.method]]
    id = "pango_attr_list_get_iterator"
    bind = false
    # Not needed ?

  [[PangoAttrList.method]]
    id = "pango_attr_list_get_type"
    ada = "Get_Type_Attr_List"

  [[PangoAttrList.method]]
    id = "pango_attr_list_get_attributes"
    bind = false

  [[PangoAttrList.method]]
    id = "pango_attr_list_equal"
    bind = false
    # more recent than 1.44