# ============================================================
#   PangoFont
# ============================================================

[[parameter]]
name = "self"
ada = "Font"

[[method]]
id = "pango_font_get_type"
ada = "Font_Get_Type"

[[method]]
id = "pango_font_find_shaper"
bind = false
# internal implementation of gtk

[[method]]
id = "pango_font_describe"
classwide = true

[[method]]
id = "pango_font_describe_with_absolute_size"
classwide = true

[[method]]
id = "pango_font_descriptions_free"
bind = false
# in Ada, need iteration

[[method]]
id = "pango_font_get_features"
bind = false
# Harfbuzz required

[[method]]
id = "pango_font_get_hb_font"
bind = false
# Harfbuzz required

[[method]]
id = "pango_font_get_metrics"

[[method.parameter]]
name = "language"
default = "Pango.Language.Null_Pango_Language"

[extra]

# Pango.Font_Map and Pango.Font_Face both with Pango.Font, so the full
# view can only be had in the body.
[[extra.with_spec]]
pkg = "Pango.Font_Face"
limited = true

[[extra.with_spec]]
pkg = "Pango.Font_Map"
limited = true

[[extra.with_body]]
pkg = "Pango.Font_Face"

[[extra.with_body]]
pkg = "Pango.Font_Map"
