# ============================================================
#   PangoLayoutIter
# ============================================================
into = "PangoLayout"

[[method]]
id = "pango_layout_iter_get_type"
ada = "Get_Type_Layout_Iter"

[[method]]
id = "pango_layout_iter_get_run"
bind = false
# what is a pango_run

[[method]]
id = "pango_layout_iter_get_run_readonly"
bind = false
# what is a pango_run