# ============================================================
#   PangoTabArray
# ============================================================
ada = "Pango.Tabs"

[[enum]]
ctype = "PangoTabAlign"

[[method]]
id = "pango_tab_array_get_tabs"
bind = false
# Require manual binding