
# ============================================================
#   PangoFontset
# ============================================================
[PangoFontset]

  [PangoFontset.doc]
    text = "an object containing a set of pango.Font objects"