# ============================================================
#   Utils
# ============================================================
ada = "Glib.Utils"

[[constant]]
prefix_regexp = "GLIB_\\w*_VERSION"
prefix = "GLIB_"

[[function]]
id = "glib_check_version"
bind = true

[[function]]
id = "g_get_home_dir"
bind = true
# From doc:
# "The returned string is owned by GLib and must not be modified or freed."