
all::
	${MAKE} -C gtkada_rm
	${MAKE} -C gtkada_ug html latexpdf

clean::
	${MAKE} -C gtkada_rm clean
	${MAKE} -C gtkada_ug clean

distclean::
	${MAKE} -C gtkada_rm distclean
	${MAKE} -C gtkada_ug distclean
