
/* This file is automatically generated from the .gir files */
#include <gtk/gtk.h>

GtkAdjustment* gtkada_Progress_get_adjustment (GtkProgress* self) {
    return self->adjustment;
}

guint gtkada_Progress_get_activity_mode (GtkProgress* self) {
    return self->activity_mode;
}
