/*****************************************************************************
 *               GtkAda - Ada95 binding for Gtk+/Gnome                       *
 *                                                                           *
 *   Copyright (C) 1998-2000 E. Briot, J. Brobecker and A. Charlet           *
 *                     Copyright (C) 2000-2022, AdaCore                      *
 *                                                                           *
 * This library is free software;  you can redistribute it and/or modify it  *
 * under terms of the  GNU General Public License  as published by the Free  *
 * Software  Foundation;  either version 3,  or (at your  option) any later  *
 * version. This library is distributed in the hope that it will be useful,  *
 * but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN-  *
 * TABILITY or FITNESS FOR A PARTICULAR PURPOSE.                             *
 *                                                                           *
 * As a special exception under Section 7 of GPL version 3, you are granted  *
 * additional permissions described in the GCC Runtime Library Exception,    *
 * version 3.1, as published by the Free Software Foundation.                *
 *                                                                           *
 * You should have received a copy of the GNU General Public License and     *
 * a copy of the GCC Runtime Library Exception along with this program;      *
 * see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see     *
 * <http://www.gnu.org/licenses/>.                                           *
 *
 *****************************************************************************

This file is automatically generated from the .gir files
*/
#include <gtk/gtk.h>

void gtkada_Accessible_set_get_accessible_id(GtkAccessibleInterface* iface, void* handler) {
    iface->get_accessible_id = handler;
}

void gtkada_Accessible_set_get_accessible_parent(GtkAccessibleInterface* iface, void* handler) {
    iface->get_accessible_parent = handler;
}

void gtkada_Accessible_set_get_at_context(GtkAccessibleInterface* iface, void* handler) {
    iface->get_at_context = handler;
}

void gtkada_Accessible_set_get_bounds(GtkAccessibleInterface* iface, void* handler) {
    iface->get_bounds = handler;
}

void gtkada_Accessible_set_get_first_accessible_child(GtkAccessibleInterface* iface, void* handler) {
    iface->get_first_accessible_child = handler;
}

void gtkada_Accessible_set_get_next_accessible_sibling(GtkAccessibleInterface* iface, void* handler) {
    iface->get_next_accessible_sibling = handler;
}

void gtkada_Accessible_set_get_platform_state(GtkAccessibleInterface* iface, void* handler) {
    iface->get_platform_state = handler;
}

void gtkada_Accessible_Text_set_get_attributes(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_attributes = handler;
}

void gtkada_Accessible_Text_set_get_caret_position(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_caret_position = handler;
}

void gtkada_Accessible_Text_set_get_contents(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_contents = handler;
}

void gtkada_Accessible_Text_set_get_contents_at(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_contents_at = handler;
}

void gtkada_Accessible_Text_set_get_default_attributes(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_default_attributes = handler;
}

void gtkada_Accessible_Text_set_get_extents(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_extents = handler;
}

void gtkada_Accessible_Text_set_get_offset(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_offset = handler;
}

void gtkada_Accessible_Text_set_get_selection(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_selection = handler;
}

void gtkada_Accessible_Text_set_set_caret_position(GtkAccessibleTextInterface* iface, void* handler) {
    iface->set_caret_position = handler;
}

void gtkada_Accessible_Text_set_set_selection(GtkAccessibleTextInterface* iface, void* handler) {
    iface->set_selection = handler;
}

void gtkada_Accessible_Hypertext_set_get_link(GtkAccessibleHypertextInterface* iface, void* handler) {
    iface->get_link = handler;
}

void gtkada_Accessible_Hypertext_set_get_link_at(GtkAccessibleHypertextInterface* iface, void* handler) {
    iface->get_link_at = handler;
}

void gtkada_Accessible_Hypertext_set_get_n_links(GtkAccessibleHypertextInterface* iface, void* handler) {
    iface->get_n_links = handler;
}

void gtkada_Application_set_command_line(GApplicationClass* iface, void* handler) {
    iface->command_line = handler;
}

void gtkada_Application_set_local_command_line(GApplicationClass* iface, void* handler) {
    iface->local_command_line = handler;
}
