/*****************************************************************************
 *               GtkAda - Ada95 binding for Gtk+/Gnome                       *
 *                                                                           *
 *   Copyright (C) 1998-2000 E. Briot, J. Brobecker and A. Charlet           *
 *                     Copyright (C) 2000-2026, AdaCore                      *
 *                                                                           *
 * This library is free software;  you can redistribute it and/or modify it  *
 * under terms of the  GNU General Public License  as published by the Free  *
 * Software  Foundation;  either version 3,  or (at your  option) any later  *
 * version. This library is distributed in the hope that it will be useful,  *
 * but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN-  *
 * TABILITY or FITNESS FOR A PARTICULAR PURPOSE.                             *
 *                                                                           *
 * As a special exception under Section 7 of GPL version 3, you are granted  *
 * additional permissions described in the GCC Runtime Library Exception,    *
 * version 3.1, as published by the Free Software Foundation.                *
 *                                                                           *
 * You should have received a copy of the GNU General Public License and     *
 * a copy of the GCC Runtime Library Exception along with this program;      *
 * see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see     *
 * <http://www.gnu.org/licenses/>.                                           *
 *
 *****************************************************************************

This file is automatically generated from the .gir files
*/
#include <gtk/gtk.h>

void gtkada_Accessible_set_get_accessible_id(GtkAccessibleInterface* iface, void* handler) {
    iface->get_accessible_id = handler;
}

void gtkada_Accessible_set_get_accessible_parent(GtkAccessibleInterface* iface, void* handler) {
    iface->get_accessible_parent = handler;
}

void gtkada_Accessible_set_get_at_context(GtkAccessibleInterface* iface, void* handler) {
    iface->get_at_context = handler;
}

void gtkada_Accessible_set_get_bounds(GtkAccessibleInterface* iface, void* handler) {
    iface->get_bounds = handler;
}

void gtkada_Accessible_set_get_first_accessible_child(GtkAccessibleInterface* iface, void* handler) {
    iface->get_first_accessible_child = handler;
}

void gtkada_Accessible_set_get_next_accessible_sibling(GtkAccessibleInterface* iface, void* handler) {
    iface->get_next_accessible_sibling = handler;
}

void gtkada_Accessible_set_get_platform_state(GtkAccessibleInterface* iface, void* handler) {
    iface->get_platform_state = handler;
}

void gtkada_Accessible_Text_set_get_attributes(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_attributes = handler;
}

void gtkada_Accessible_Text_set_get_caret_position(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_caret_position = handler;
}

void gtkada_Accessible_Text_set_get_contents(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_contents = handler;
}

void gtkada_Accessible_Text_set_get_contents_at(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_contents_at = handler;
}

void gtkada_Accessible_Text_set_get_default_attributes(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_default_attributes = handler;
}

void gtkada_Accessible_Text_set_get_extents(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_extents = handler;
}

void gtkada_Accessible_Text_set_get_offset(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_offset = handler;
}

void gtkada_Accessible_Text_set_get_selection(GtkAccessibleTextInterface* iface, void* handler) {
    iface->get_selection = handler;
}

void gtkada_Accessible_Text_set_set_caret_position(GtkAccessibleTextInterface* iface, void* handler) {
    iface->set_caret_position = handler;
}

void gtkada_Accessible_Text_set_set_selection(GtkAccessibleTextInterface* iface, void* handler) {
    iface->set_selection = handler;
}

void gtkada_Accessible_Hypertext_set_get_link(GtkAccessibleHypertextInterface* iface, void* handler) {
    iface->get_link = handler;
}

void gtkada_Accessible_Hypertext_set_get_link_at(GtkAccessibleHypertextInterface* iface, void* handler) {
    iface->get_link_at = handler;
}

void gtkada_Accessible_Hypertext_set_get_n_links(GtkAccessibleHypertextInterface* iface, void* handler) {
    iface->get_n_links = handler;
}

void gtkada_Cell_Editable_set_editing_done(GtkCellEditableIface* iface, void* handler) {
    iface->editing_done = handler;
}

void gtkada_Cell_Editable_set_remove_widget(GtkCellEditableIface* iface, void* handler) {
    iface->remove_widget = handler;
}

void gtkada_Shortcut_Manager_set_add_controller(GtkShortcutManagerInterface* iface, void* handler) {
    iface->add_controller = handler;
}

void gtkada_Shortcut_Manager_set_remove_controller(GtkShortcutManagerInterface* iface, void* handler) {
    iface->remove_controller = handler;
}

void gtkada_Tree_Model_set_get_column_type(GtkTreeModelIface* iface, void* handler) {
    iface->get_column_type = handler;
}

void gtkada_Tree_Model_set_get_flags(GtkTreeModelIface* iface, void* handler) {
    iface->get_flags = handler;
}

void gtkada_Tree_Model_set_get_iter(GtkTreeModelIface* iface, void* handler) {
    iface->get_iter = handler;
}

void gtkada_Tree_Model_set_get_n_columns(GtkTreeModelIface* iface, void* handler) {
    iface->get_n_columns = handler;
}

void gtkada_Tree_Model_set_get_path(GtkTreeModelIface* iface, void* handler) {
    iface->get_path = handler;
}

void gtkada_Tree_Model_set_get_value(GtkTreeModelIface* iface, void* handler) {
    iface->get_value = handler;
}

void gtkada_Tree_Model_set_iter_children(GtkTreeModelIface* iface, void* handler) {
    iface->iter_children = handler;
}

void gtkada_Tree_Model_set_iter_has_child(GtkTreeModelIface* iface, void* handler) {
    iface->iter_has_child = handler;
}

void gtkada_Tree_Model_set_iter_n_children(GtkTreeModelIface* iface, void* handler) {
    iface->iter_n_children = handler;
}

void gtkada_Tree_Model_set_iter_next(GtkTreeModelIface* iface, void* handler) {
    iface->iter_next = handler;
}

void gtkada_Tree_Model_set_iter_nth_child(GtkTreeModelIface* iface, void* handler) {
    iface->iter_nth_child = handler;
}

void gtkada_Tree_Model_set_iter_parent(GtkTreeModelIface* iface, void* handler) {
    iface->iter_parent = handler;
}

void gtkada_Tree_Model_set_iter_previous(GtkTreeModelIface* iface, void* handler) {
    iface->iter_previous = handler;
}

void gtkada_Tree_Model_set_ref_node(GtkTreeModelIface* iface, void* handler) {
    iface->ref_node = handler;
}

void gtkada_Tree_Model_set_row_changed(GtkTreeModelIface* iface, void* handler) {
    iface->row_changed = handler;
}

void gtkada_Tree_Model_set_row_deleted(GtkTreeModelIface* iface, void* handler) {
    iface->row_deleted = handler;
}

void gtkada_Tree_Model_set_row_has_child_toggled(GtkTreeModelIface* iface, void* handler) {
    iface->row_has_child_toggled = handler;
}

void gtkada_Tree_Model_set_row_inserted(GtkTreeModelIface* iface, void* handler) {
    iface->row_inserted = handler;
}

void gtkada_Tree_Model_set_rows_reordered(GtkTreeModelIface* iface, void* handler) {
    iface->rows_reordered = handler;
}

void gtkada_Tree_Model_set_unref_node(GtkTreeModelIface* iface, void* handler) {
    iface->unref_node = handler;
}

void gtkada_Action_set_activate(GActionInterface* iface, void* handler) {
    iface->activate = handler;
}

void gtkada_Action_set_change_state(GActionInterface* iface, void* handler) {
    iface->change_state = handler;
}

void gtkada_Action_set_get_enabled(GActionInterface* iface, void* handler) {
    iface->get_enabled = handler;
}

void gtkada_Action_set_get_name(GActionInterface* iface, void* handler) {
    iface->get_name = handler;
}

void gtkada_Action_set_get_parameter_type(GActionInterface* iface, void* handler) {
    iface->get_parameter_type = handler;
}

void gtkada_Action_set_get_state(GActionInterface* iface, void* handler) {
    iface->get_state = handler;
}

void gtkada_Action_set_get_state_hint(GActionInterface* iface, void* handler) {
    iface->get_state_hint = handler;
}

void gtkada_Action_set_get_state_type(GActionInterface* iface, void* handler) {
    iface->get_state_type = handler;
}

void gtkada_Action_Group_set_action_added(GActionGroupInterface* iface, void* handler) {
    iface->action_added = handler;
}

void gtkada_Action_Group_set_action_enabled_changed(GActionGroupInterface* iface, void* handler) {
    iface->action_enabled_changed = handler;
}

void gtkada_Action_Group_set_action_removed(GActionGroupInterface* iface, void* handler) {
    iface->action_removed = handler;
}

void gtkada_Action_Group_set_action_state_changed(GActionGroupInterface* iface, void* handler) {
    iface->action_state_changed = handler;
}

void gtkada_Action_Group_set_activate_action(GActionGroupInterface* iface, void* handler) {
    iface->activate_action = handler;
}

void gtkada_Action_Group_set_change_action_state(GActionGroupInterface* iface, void* handler) {
    iface->change_action_state = handler;
}

void gtkada_Action_Group_set_get_action_enabled(GActionGroupInterface* iface, void* handler) {
    iface->get_action_enabled = handler;
}

void gtkada_Action_Group_set_get_action_parameter_type(GActionGroupInterface* iface, void* handler) {
    iface->get_action_parameter_type = handler;
}

void gtkada_Action_Group_set_get_action_state(GActionGroupInterface* iface, void* handler) {
    iface->get_action_state = handler;
}

void gtkada_Action_Group_set_get_action_state_hint(GActionGroupInterface* iface, void* handler) {
    iface->get_action_state_hint = handler;
}

void gtkada_Action_Group_set_get_action_state_type(GActionGroupInterface* iface, void* handler) {
    iface->get_action_state_type = handler;
}

void gtkada_Action_Group_set_has_action(GActionGroupInterface* iface, void* handler) {
    iface->has_action = handler;
}

void gtkada_Action_Group_set_list_actions(GActionGroupInterface* iface, void* handler) {
    iface->list_actions = handler;
}

void gtkada_Action_Group_set_query_action(GActionGroupInterface* iface, void* handler) {
    iface->query_action = handler;
}

void gtkada_Action_Map_set_add_action(GActionMapInterface* iface, void* handler) {
    iface->add_action = handler;
}

void gtkada_Action_Map_set_lookup_action(GActionMapInterface* iface, void* handler) {
    iface->lookup_action = handler;
}

void gtkada_Action_Map_set_remove_action(GActionMapInterface* iface, void* handler) {
    iface->remove_action = handler;
}

void gtkada_List_Model_set_get_item(GListModelInterface* iface, void* handler) {
    iface->get_item = handler;
}

void gtkada_List_Model_set_get_item_type(GListModelInterface* iface, void* handler) {
    iface->get_item_type = handler;
}

void gtkada_List_Model_set_get_n_items(GListModelInterface* iface, void* handler) {
    iface->get_n_items = handler;
}

void gtkada_Application_set_command_line(GApplicationClass* iface, void* handler) {
    iface->command_line = handler;
}

void gtkada_Application_set_local_command_line(GApplicationClass* iface, void* handler) {
    iface->local_command_line = handler;
}
