\input texinfo   @c -*-texinfo-*-
@settitle GtkAda Reference Manual
@setfilename gtkada_rm.info
@syncodeindex fn cp

@c --------------------------------------------
@finalout
@c --------------------------------------------


@titlepage
@title GtkAda Reference Manual
@subtitle Version 1.2.5
@subtitle Document revision level $Revision$
@subtitle Date: $Date$
@author E. Briot, J. Brobecker, A. Charlet
     
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1999-2000 E.Briot, J.Brobecker, A. Charlet
@end titlepage


@ifinfo
@node Top
@top GtkAda Reference Manual

@menu
* The detailed documentation for packages::
* Index::

@detailmenu
 --- The Detailed Node Listing ---

The detailed documentation for packages
@include generated_menu.texi

@end detailmenu
@end menu
@end ifinfo

@node The detailed documentation for packages
@chapter  The detailed documentation for packages

This section describes all the packages included in GtkAda.
All the widgets are described, as well as their associated subprograms

@include generated_submenu.texi

@include generated.texi

@node Index
@unnumbered Index
@printindex cp

@contents
@bye
