\input texinfo   @c -*-texinfo-*-
@settitle GtkAda User's Guide
@setfilename func.info
@syncodeindex fn cp

@titlepage
@title GtkAda User's Guide
@subtitle Version 1.2.5
@subtitle Document revision level $Revision$
@subtitle Date: $Date$
@author E. Briot, J. Brobecker, A. Charlet, P. Durif
     
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1999 E.Briot, A.Charlet, J.Brobecker
@end titlepage


@ifinfo
@node Top
@top GtkAda user's guide

@menu
* The detailed documentation for packages::
* Index::

@detailmenu
 --- The Detailed Node Listing ---

The detailed documentation for packages

* Package Gtk.Object::
* Package Gtk.Widget::
* Package Gtk.Container::
* Package Gtk.Bin::
* Package Gtk.Button::
@include generated_menu.texi

@end detailmenu
@end menu
@end ifinfo

@node The detailed documentation for packages
@chapter  The detailed documentation for packages

This section describes all the packages included in GtkAda.
All the widgets are described, as well as their associated subprograms

@menu
* Package Gtk.Object::
* Package Gtk.Widget::
* Package Gtk.Container::
* Package Gtk.Bin::
* Package Gtk.Button::
* Package Gtk.Check_Button::
* Package Gtk.Toggle_Button::
@end menu


@node Package Gtk.Object
@section Package Gtk.Object

@node Package Gtk.Widget
@section Package Gtk.Widget

@node Package Gtk.Container
@section Package Gtk.Container

@node Package Gtk.Bin
@section Package Gtk.Bin

@node Package Gtk.Button
@section Package Gtk.Button

@include generated.texi

@node Index
@unnumbered Index
@printindex cp

@contents
@bye
