\input texinfo   @c -*-texinfo-*-
@settitle GtkAda Reference Manual
@setfilename gtkada_rm.info
@syncodeindex fn cp

@dircategory User Interface Toolkit
@direntry
* GtkAda_Rm: (gtkada_rm).           Ada95 graphical tookit based on GTK+ (Reference Manual)
@end direntry 

@c --------------------------------------------
@finalout
@c --------------------------------------------


@titlepage
@title GtkAda Reference Manual
@subtitle Version 2.8.0
@subtitle Document revision level $Revision$
@subtitle Date: $Date$
@author E. Briot, J. Brobecker, A. Charlet
     
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1998-2000, Emmanuel Briot, Joel Brobecker, Arnaud Charlet

Copyright @copyright{} 2000-2006, AdaCore
@end titlepage


@ifnottex
@node Top
@top GtkAda Reference Manual

@include generated_menu.texi
@end ifnottex

@include generated.texi

@node Index
@unnumbered Index
@printindex cp

@contents
@bye
